//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\webauthn.dll
// Interface ID: 1495a2be-b7a8-4299-9d3b-8825e5bcbfb9
// Interface Version: 1.0



namespace rpc_1495a2be_b7a8_4299_9d3b_8825e5bcbfb9_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_1(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public byte[] Read_0()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_1()
        {
            return ReadConformantArray<byte>();
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("1495a2be-b7a8-4299-9d3b-8825e5bcbfb9", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        // async
        public int s_SSCtapCommand(byte[] p0, int p1, out byte[] p2, out int p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_0(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"), p1);
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(0, m);
            p2 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_1), false);
            p3 = u.ReadInt32();
            return u.ReadInt32();
        }
    }
    #endregion
}

