//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\pla.dll
// Interface ID: 647d4452-9f33-4a18-b2be-c5c0e920e94e
// Interface Version: 1.0



namespace rpc_647d4452_9f33_4a18_b2be_c5c0e920e94e_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
        public void Write_1(Struct_1 p0)
        {
            WriteStruct<Struct_1>(p0);
        }
        public void Write_2(Struct_2 p0)
        {
            WriteStruct<Struct_2>(p0);
        }
        public void Write_3(Struct_3 p0)
        {
            WriteStruct<Struct_3>(p0);
        }
        public void Write_4(Union_4 p0)
        {
            WriteStruct<Union_4>(p0);
        }
        public void Write_5(Struct_5 p0)
        {
            WriteStruct<Struct_5>(p0);
        }
        public void Write_6(Struct_6 p0)
        {
            WriteStruct<Struct_6>(p0);
        }
        public void Write_7(Struct_7 p0)
        {
            WriteStruct<Struct_7>(p0);
        }
        public void Write_8(Struct_8 p0)
        {
            WriteStruct<Struct_8>(p0);
        }
        public void Write_9(Struct_9 p0)
        {
            WriteStruct<Struct_9>(p0);
        }
        public void Write_10(Union_10 p0, long p1)
        {
            WriteUnion<Union_10>(p0, p1);
        }
        public void Write_11(Struct_11 p0)
        {
            WriteStruct<Struct_11>(p0);
        }
        public void Write_12(Struct_12 p0)
        {
            WriteStruct<Struct_12>(p0);
        }
        public void Write_13(Struct_13 p0)
        {
            WriteStruct<Struct_13>(p0);
        }
        public void Write_14(Struct_14 p0)
        {
            WriteStruct<Struct_14>(p0);
        }
        public void Write_15(Struct_15 p0)
        {
            WriteStruct<Struct_15>(p0);
        }
        public void Write_16(Struct_17 p0)
        {
            WriteStruct<Struct_17>(p0);
        }
        public void Write_17(Struct_18 p0)
        {
            WriteStruct<Struct_18>(p0);
        }
        public void Write_18(Struct_19 p0)
        {
            WriteStruct<Struct_19>(p0);
        }
        public void Write_19(Struct_20 p0)
        {
            WriteStruct<Struct_20>(p0);
        }
        public void Write_20(NtApiDotNet.Ndr.Marshal.NdrUnsupported p0)
        {
            WriteUnsupported(p0, "FC_USER_MARSHAL - BSTR");
        }
        public void Write_21(short[] p0, long p1)
        {
            WriteConformantArray<short>(p0, p1);
        }
        public void Write_22(Struct_3[] p0, long p1)
        {
            WriteConformantArray<Struct_3>(p0, p1);
        }
        public void Write_23(Struct_1[] p0, long p1)
        {
            WriteConformantStructArray<Struct_1>(p0, p1);
        }
        public void Write_24(NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[] p0, long p1)
        {
            WriteConformantArrayCallback<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(p0, new System.Action<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(this.WriteInterfacePointer), p1);
        }
        public void Write_25(NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[] p0, long p1)
        {
            WriteConformantArrayCallback<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(p0, new System.Action<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(this.WriteInterfacePointer), p1);
        }
        public void Write_26(Struct_9[] p0, long p1)
        {
            WriteConformantStructArray<Struct_9>(p0, p1);
        }
        public void Write_27(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_28(Struct_12[] p0, long p1)
        {
            WriteConformantStructArray<Struct_12>(p0, p1);
        }
        public void Write_29(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_30(short[] p0, long p1)
        {
            WriteConformantArray<short>(p0, p1);
        }
        public void Write_31(int[] p0, long p1)
        {
            WriteConformantArray<int>(p0, p1);
        }
        public void Write_32(long[] p0, long p1)
        {
            WriteConformantArray<long>(p0, p1);
        }
        public void Write_33(NtApiDotNet.Ndr.Marshal.NdrUnsupported p0)
        {
            WriteUnsupported(p0, "FC_USER_MARSHAL - LPSAFEARRAY");
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
        public Struct_1 Read_1()
        {
            return ReadStruct<Struct_1>();
        }
        public Struct_2 Read_2()
        {
            return ReadStruct<Struct_2>();
        }
        public Struct_3 Read_3()
        {
            return ReadStruct<Struct_3>();
        }
        public Union_4 Read_4()
        {
            return ReadStruct<Union_4>();
        }
        public Struct_5 Read_5()
        {
            return ReadStruct<Struct_5>();
        }
        public Struct_6 Read_6()
        {
            return ReadStruct<Struct_6>();
        }
        public Struct_7 Read_7()
        {
            return ReadStruct<Struct_7>();
        }
        public Struct_8 Read_8()
        {
            return ReadStruct<Struct_8>();
        }
        public Struct_9 Read_9()
        {
            return ReadStruct<Struct_9>();
        }
        public Union_10 Read_10()
        {
            return ReadStruct<Union_10>();
        }
        public Struct_11 Read_11()
        {
            return ReadStruct<Struct_11>();
        }
        public Struct_12 Read_12()
        {
            return ReadStruct<Struct_12>();
        }
        public Struct_13 Read_13()
        {
            return ReadStruct<Struct_13>();
        }
        public Struct_14 Read_14()
        {
            return ReadStruct<Struct_14>();
        }
        public Struct_15 Read_15()
        {
            return ReadStruct<Struct_15>();
        }
        public Struct_17 Read_16()
        {
            return ReadStruct<Struct_17>();
        }
        public Struct_18 Read_17()
        {
            return ReadStruct<Struct_18>();
        }
        public Struct_19 Read_18()
        {
            return ReadStruct<Struct_19>();
        }
        public Struct_20 Read_19()
        {
            return ReadStruct<Struct_20>();
        }
        public NtApiDotNet.Ndr.Marshal.NdrUnsupported Read_20()
        {
            return ReadUnsupported("FC_USER_MARSHAL - BSTR");
        }
        public short[] Read_21()
        {
            return ReadConformantArray<short>();
        }
        public Struct_3[] Read_22()
        {
            return ReadConformantArray<Struct_3>();
        }
        public Struct_1[] Read_23()
        {
            return ReadConformantStructArray<Struct_1>();
        }
        public NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[] Read_24()
        {
            return ReadConformantArrayCallback<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(new System.Func<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(this.ReadInterfacePointer));
        }
        public NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[] Read_25()
        {
            return ReadConformantArrayCallback<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(new System.Func<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(this.ReadInterfacePointer));
        }
        public Struct_9[] Read_26()
        {
            return ReadConformantStructArray<Struct_9>();
        }
        public byte[] Read_27()
        {
            return ReadConformantArray<byte>();
        }
        public Struct_12[] Read_28()
        {
            return ReadConformantStructArray<Struct_12>();
        }
        public byte[] Read_29()
        {
            return ReadConformantArray<byte>();
        }
        public short[] Read_30()
        {
            return ReadConformantArray<short>();
        }
        public int[] Read_31()
        {
            return ReadConformantArray<int>();
        }
        public long[] Read_32()
        {
            return ReadConformantArray<long>();
        }
        public NtApiDotNet.Ndr.Marshal.NdrUnsupported Read_33()
        {
            return ReadUnsupported("FC_USER_MARSHAL - LPSAFEARRAY");
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_20(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member0, "Member0"));
            m.WriteUInt3264(Member8);
            m.WriteUInt3264(Member10);
            m.WriteUInt3264(Member18);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_20();
            Member8 = u.ReadUInt3264();
            Member10 = u.ReadUInt3264();
            Member18 = u.ReadUInt3264();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public NtApiDotNet.Ndr.Marshal.NdrUnsupported Member0;
        public NtApiDotNet.Ndr.Marshal.NdrUInt3264 Member8;
        public NtApiDotNet.Ndr.Marshal.NdrUInt3264 Member10;
        public NtApiDotNet.Ndr.Marshal.NdrUInt3264 Member18;
        public static Struct_0 CreateDefault()
        {
            return new Struct_0();
        }
        public Struct_0(NtApiDotNet.Ndr.Marshal.NdrUnsupported Member0, NtApiDotNet.Ndr.Marshal.NdrUInt3264 Member8, NtApiDotNet.Ndr.Marshal.NdrUInt3264 Member10, NtApiDotNet.Ndr.Marshal.NdrUInt3264 Member18)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
        }
    }
    public struct Struct_1 : NtApiDotNet.Ndr.Marshal.INdrConformantStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.Write_21(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member8, "Member8"), Member4);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.Read_21();
        }
        int NtApiDotNet.Ndr.Marshal.INdrConformantStructure.GetConformantDimensions()
        {
            return 1;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public short[] Member8;
        public static Struct_1 CreateDefault()
        {
            Struct_1 ret = new Struct_1();
            ret.Member8 = new short[0];
            return ret;
        }
        public Struct_1(int Member0, int Member4, short[] Member8)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
        }
    }
    public struct Struct_2 : NtApiDotNet.Ndr.Marshal.INdrConformantStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt16(Member0);
            m.WriteInt16(Member2);
            m.WriteInt32(Member4);
            m.WriteInt32(Member8);
            m.Write_4(Member10);
            m.Write_22(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member38, "Member38"), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt16();
            Member2 = u.ReadInt16();
            Member4 = u.ReadInt32();
            Member8 = u.ReadInt32();
            Member10 = u.Read_4();
            Member38 = u.Read_22();
        }
        int NtApiDotNet.Ndr.Marshal.INdrConformantStructure.GetConformantDimensions()
        {
            return 1;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public short Member0;
        public short Member2;
        public int Member4;
        public int Member8;
        public Union_4 Member10;
        public Struct_3[] Member38;
        public static Struct_2 CreateDefault()
        {
            Struct_2 ret = new Struct_2();
            ret.Member38 = new Struct_3[0];
            return ret;
        }
        public Struct_2(short Member0, short Member2, int Member4, int Member8, Union_4 Member10, Struct_3[] Member38)
        {
            this.Member0 = Member0;
            this.Member2 = Member2;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member38 = Member38;
        }
    }
    public struct Struct_3 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public static Struct_3 CreateDefault()
        {
            return new Struct_3();
        }
        public Struct_3(int Member0, int Member4)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
        }
    }
    public struct Union_4 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteUInt32(Selector);
            if ((Selector == 8))
            {
                m.Write_5(Arm_8);
                goto done;
            }
            if ((Selector == 13))
            {
                m.Write_6(Arm_13);
                goto done;
            }
            if ((Selector == 9))
            {
                m.Write_7(Arm_9);
                goto done;
            }
            if ((Selector == 12))
            {
                m.Write_8(Arm_12);
                goto done;
            }
            if ((Selector == 36))
            {
                m.Write_14(Arm_36);
                goto done;
            }
            if ((Selector == 32781))
            {
                m.Write_15(Arm_32781);
                goto done;
            }
            if ((Selector == 16))
            {
                m.Write_16(Arm_16);
                goto done;
            }
            if ((Selector == 2))
            {
                m.Write_17(Arm_2);
                goto done;
            }
            if ((Selector == 3))
            {
                m.Write_18(Arm_3);
                goto done;
            }
            if ((Selector == 20))
            {
                m.Write_19(Arm_20);
                goto done;
            }
            throw new System.ArgumentException("No matching union selector when marshaling Union_4");
        done:
            return;
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Selector = u.ReadUInt32();
            if ((Selector == 8))
            {
                Arm_8 = u.Read_5();
                goto done;
            }
            if ((Selector == 13))
            {
                Arm_13 = u.Read_6();
                goto done;
            }
            if ((Selector == 9))
            {
                Arm_9 = u.Read_7();
                goto done;
            }
            if ((Selector == 12))
            {
                Arm_12 = u.Read_8();
                goto done;
            }
            if ((Selector == 36))
            {
                Arm_36 = u.Read_14();
                goto done;
            }
            if ((Selector == 32781))
            {
                Arm_32781 = u.Read_15();
                goto done;
            }
            if ((Selector == 16))
            {
                Arm_16 = u.Read_16();
                goto done;
            }
            if ((Selector == 2))
            {
                Arm_2 = u.Read_17();
                goto done;
            }
            if ((Selector == 3))
            {
                Arm_3 = u.Read_18();
                goto done;
            }
            if ((Selector == 20))
            {
                Arm_20 = u.Read_19();
                goto done;
            }
            throw new System.ArgumentException("No matching union selector when marshaling Union_4");
        done:
            return;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 1;
        }
        public uint Selector;
        public Struct_5 Arm_8;
        public Struct_6 Arm_13;
        public Struct_7 Arm_9;
        public Struct_8 Arm_12;
        public Struct_14 Arm_36;
        public Struct_15 Arm_32781;
        public Struct_17 Arm_16;
        public Struct_18 Arm_2;
        public Struct_19 Arm_3;
        public Struct_20 Arm_20;
        public static Union_4 CreateDefault()
        {
            return new Union_4();
        }
        public Union_4(uint Selector, Struct_5 Arm_8, Struct_6 Arm_13, Struct_7 Arm_9, Struct_8 Arm_12, Struct_14 Arm_36, Struct_15 Arm_32781, Struct_17 Arm_16, Struct_18 Arm_2, Struct_19 Arm_3, Struct_20 Arm_20)
        {
            this.Selector = Selector;
            this.Arm_8 = Arm_8;
            this.Arm_13 = Arm_13;
            this.Arm_9 = Arm_9;
            this.Arm_12 = Arm_12;
            this.Arm_36 = Arm_36;
            this.Arm_32781 = Arm_32781;
            this.Arm_16 = Arm_16;
            this.Arm_2 = Arm_2;
            this.Arm_3 = Arm_3;
            this.Arm_20 = Arm_20;
        }
    }
    public struct Struct_5 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<Struct_1[], long>(Member8, new System.Action<Struct_1[], long>(m.Write_23), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<Struct_1[]>(new System.Func<Struct_1[]>(u.Read_23), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_1[]> Member8;
        public static Struct_5 CreateDefault()
        {
            Struct_5 ret = new Struct_5();
            ret.Member8 = new Struct_1[0];
            return ret;
        }
        public Struct_5(int Member0, Struct_1[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_6 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[], long>(Member8, new System.Action<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[], long>(m.Write_24), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[]>(new System.Func<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[]>(u.Read_24), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[]> Member8;
        public static Struct_6 CreateDefault()
        {
            Struct_6 ret = new Struct_6();
            ret.Member8 = new NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[0];
            return ret;
        }
        public Struct_6(int Member0, NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_7 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[], long>(Member8, new System.Action<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[], long>(m.Write_25), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[]>(new System.Func<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[]>(u.Read_25), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[]> Member8;
        public static Struct_7 CreateDefault()
        {
            Struct_7 ret = new Struct_7();
            ret.Member8 = new NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[0];
            return ret;
        }
        public Struct_7(int Member0, NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_8 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<Struct_9[], long>(Member8, new System.Action<Struct_9[], long>(m.Write_26), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<Struct_9[]>(new System.Func<Struct_9[]>(u.Read_26), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_9[]> Member8;
        public static Struct_8 CreateDefault()
        {
            Struct_8 ret = new Struct_8();
            ret.Member8 = new Struct_9[0];
            return ret;
        }
        public Struct_8(int Member0, Struct_9[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_9 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.WriteInt16(Member8);
            m.WriteInt16(MemberA);
            m.WriteInt16(MemberC);
            m.WriteInt16(MemberE);
            m.Write_10(Member10, Member8);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.ReadInt16();
            MemberA = u.ReadInt16();
            MemberC = u.ReadInt16();
            MemberE = u.ReadInt16();
            Member10 = u.Read_10();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public int Member0;
        public int Member4;
        public short Member8;
        public short MemberA;
        public short MemberC;
        public short MemberE;
        public Union_10 Member10;
        public static Struct_9 CreateDefault()
        {
            return new Struct_9();
        }
        public Struct_9(int Member0, int Member4, short Member8, short MemberA, short MemberC, short MemberE, Union_10 Member10)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.MemberA = MemberA;
            this.MemberC = MemberC;
            this.MemberE = MemberE;
            this.Member10 = Member10;
        }
    }
    public struct Union_10 : NtApiDotNet.Ndr.Marshal.INdrNonEncapsulatedUnion
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            throw new System.NotImplementedException();
        }
        void NtApiDotNet.Ndr.Marshal.INdrNonEncapsulatedUnion.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m, long l)
        {
            Selector = ((uint)(l));
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteUInt32(Selector);
            if ((Selector == 20))
            {
                m.WriteInt64(Arm_20);
                goto done;
            }
            if ((Selector == 3))
            {
                m.WriteInt32(Arm_3);
                goto done;
            }
            if ((Selector == 17))
            {
                m.WriteByte(Arm_17);
                goto done;
            }
            if ((Selector == 2))
            {
                m.WriteInt16(Arm_2);
                goto done;
            }
            if ((Selector == 4))
            {
                m.WriteFloat(Arm_4);
                goto done;
            }
            if ((Selector == 5))
            {
                m.WriteDouble(Arm_5);
                goto done;
            }
            if ((Selector == 11))
            {
                m.WriteInt16(Arm_11);
                goto done;
            }
            if ((Selector == 10))
            {
                m.WriteInt32(Arm_10);
                goto done;
            }
            if ((Selector == 6))
            {
                m.Write_11(Arm_6);
                goto done;
            }
            if ((Selector == 7))
            {
                m.WriteDouble(Arm_7);
                goto done;
            }
            if ((Selector == 8))
            {
                m.WriteEmbeddedPointer<Struct_1>(Arm_8, new System.Action<Struct_1>(m.Write_1));
                goto done;
            }
            if ((Selector == 13))
            {
                m.WriteInterfacePointer(Arm_13);
                goto done;
            }
            if ((Selector == 9))
            {
                m.WriteInterfacePointer(Arm_9);
                goto done;
            }
            if ((Selector == 8192))
            {
                m.WriteEmbeddedPointer<Struct_2>(Arm_8192, new System.Action<Struct_2>(m.Write_2));
                goto done;
            }
            if ((Selector == 36))
            {
                m.WriteEmbeddedPointer<Struct_12>(Arm_36, new System.Action<Struct_12>(m.Write_12));
                goto done;
            }
            if ((Selector == 16420))
            {
                m.WriteEmbeddedPointer<Struct_12>(Arm_16420, new System.Action<Struct_12>(m.Write_12));
                goto done;
            }
            if ((Selector == 16401))
            {
                m.WriteEmbeddedPointer<byte>(Arm_16401, new System.Action<byte>(m.WriteByte));
                goto done;
            }
            if ((Selector == 16386))
            {
                m.WriteEmbeddedPointer<short>(Arm_16386, new System.Action<short>(m.WriteInt16));
                goto done;
            }
            if ((Selector == 16387))
            {
                m.WriteEmbeddedPointer<int>(Arm_16387, new System.Action<int>(m.WriteInt32));
                goto done;
            }
            if ((Selector == 16404))
            {
                m.WriteEmbeddedPointer<long>(Arm_16404, new System.Action<long>(m.WriteInt64));
                goto done;
            }
            if ((Selector == 16388))
            {
                m.WriteEmbeddedPointer<float>(Arm_16388, new System.Action<float>(m.WriteFloat));
                goto done;
            }
            if ((Selector == 16389))
            {
                m.WriteEmbeddedPointer<double>(Arm_16389, new System.Action<double>(m.WriteDouble));
                goto done;
            }
            if ((Selector == 16395))
            {
                m.WriteEmbeddedPointer<short>(Arm_16395, new System.Action<short>(m.WriteInt16));
                goto done;
            }
            if ((Selector == 16394))
            {
                m.WriteEmbeddedPointer<int>(Arm_16394, new System.Action<int>(m.WriteInt32));
                goto done;
            }
            if ((Selector == 16390))
            {
                m.WriteEmbeddedPointer<Struct_11>(Arm_16390, new System.Action<Struct_11>(m.Write_11));
                goto done;
            }
            if ((Selector == 16391))
            {
                m.WriteEmbeddedPointer<double>(Arm_16391, new System.Action<double>(m.WriteDouble));
                goto done;
            }
            if ((Selector == 16392))
            {
                m.WriteEmbeddedPointer<Struct_1>(Arm_16392, new System.Action<Struct_1>(m.Write_1));
                goto done;
            }
            if ((Selector == 16397))
            {
                m.WriteEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(Arm_16397, new System.Action<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(m.WriteInterfacePointer));
                goto done;
            }
            if ((Selector == 16393))
            {
                m.WriteEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(Arm_16393, new System.Action<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(m.WriteInterfacePointer));
                goto done;
            }
            if ((Selector == 24576))
            {
                m.WriteEmbeddedPointer<Struct_2>(Arm_24576, new System.Action<Struct_2>(m.Write_2));
                goto done;
            }
            if ((Selector == 16396))
            {
                m.WriteEmbeddedPointer<Struct_9>(Arm_16396, new System.Action<Struct_9>(m.Write_9));
                goto done;
            }
            if ((Selector == 16))
            {
                m.WriteSByte(Arm_16);
                goto done;
            }
            if ((Selector == 18))
            {
                m.WriteInt16(Arm_18);
                goto done;
            }
            if ((Selector == 19))
            {
                m.WriteInt32(Arm_19);
                goto done;
            }
            if ((Selector == 21))
            {
                m.WriteInt64(Arm_21);
                goto done;
            }
            if ((Selector == 22))
            {
                m.WriteInt32(Arm_22);
                goto done;
            }
            if ((Selector == 23))
            {
                m.WriteInt32(Arm_23);
                goto done;
            }
            if ((Selector == 14))
            {
                m.Write_13(Arm_14);
                goto done;
            }
            if ((Selector == 16398))
            {
                m.WriteEmbeddedPointer<Struct_13>(Arm_16398, new System.Action<Struct_13>(m.Write_13));
                goto done;
            }
            if ((Selector == 16400))
            {
                m.WriteEmbeddedPointer<sbyte>(Arm_16400, new System.Action<sbyte>(m.WriteSByte));
                goto done;
            }
            if ((Selector == 16402))
            {
                m.WriteEmbeddedPointer<short>(Arm_16402, new System.Action<short>(m.WriteInt16));
                goto done;
            }
            if ((Selector == 16403))
            {
                m.WriteEmbeddedPointer<int>(Arm_16403, new System.Action<int>(m.WriteInt32));
                goto done;
            }
            if ((Selector == 16405))
            {
                m.WriteEmbeddedPointer<long>(Arm_16405, new System.Action<long>(m.WriteInt64));
                goto done;
            }
            if ((Selector == 16406))
            {
                m.WriteEmbeddedPointer<int>(Arm_16406, new System.Action<int>(m.WriteInt32));
                goto done;
            }
            if ((Selector == 16407))
            {
                m.WriteEmbeddedPointer<int>(Arm_16407, new System.Action<int>(m.WriteInt32));
                goto done;
            }
            if ((Selector == 0))
            {
                m.WriteEmpty(Arm_0);
                goto done;
            }
            if ((Selector == 1))
            {
                m.WriteEmpty(Arm_1);
                goto done;
            }
            throw new System.ArgumentException("No matching union selector when marshaling Union_10");
        done:
            return;
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Selector = u.ReadUInt32();
            if ((Selector == 20))
            {
                Arm_20 = u.ReadInt64();
                goto done;
            }
            if ((Selector == 3))
            {
                Arm_3 = u.ReadInt32();
                goto done;
            }
            if ((Selector == 17))
            {
                Arm_17 = u.ReadByte();
                goto done;
            }
            if ((Selector == 2))
            {
                Arm_2 = u.ReadInt16();
                goto done;
            }
            if ((Selector == 4))
            {
                Arm_4 = u.ReadFloat();
                goto done;
            }
            if ((Selector == 5))
            {
                Arm_5 = u.ReadDouble();
                goto done;
            }
            if ((Selector == 11))
            {
                Arm_11 = u.ReadInt16();
                goto done;
            }
            if ((Selector == 10))
            {
                Arm_10 = u.ReadInt32();
                goto done;
            }
            if ((Selector == 6))
            {
                Arm_6 = u.Read_11();
                goto done;
            }
            if ((Selector == 7))
            {
                Arm_7 = u.ReadDouble();
                goto done;
            }
            if ((Selector == 8))
            {
                Arm_8 = u.ReadEmbeddedPointer<Struct_1>(new System.Func<Struct_1>(u.Read_1), false);
                goto done;
            }
            if ((Selector == 13))
            {
                Arm_13 = u.ReadInterfacePointer();
                goto done;
            }
            if ((Selector == 9))
            {
                Arm_9 = u.ReadInterfacePointer();
                goto done;
            }
            if ((Selector == 8192))
            {
                Arm_8192 = u.ReadEmbeddedPointer<Struct_2>(new System.Func<Struct_2>(u.Read_2), false);
                goto done;
            }
            if ((Selector == 36))
            {
                Arm_36 = u.ReadEmbeddedPointer<Struct_12>(new System.Func<Struct_12>(u.Read_12), false);
                goto done;
            }
            if ((Selector == 16420))
            {
                Arm_16420 = u.ReadEmbeddedPointer<Struct_12>(new System.Func<Struct_12>(u.Read_12), false);
                goto done;
            }
            if ((Selector == 16401))
            {
                Arm_16401 = u.ReadEmbeddedPointer<byte>(new System.Func<byte>(u.ReadByte), false);
                goto done;
            }
            if ((Selector == 16386))
            {
                Arm_16386 = u.ReadEmbeddedPointer<short>(new System.Func<short>(u.ReadInt16), false);
                goto done;
            }
            if ((Selector == 16387))
            {
                Arm_16387 = u.ReadEmbeddedPointer<int>(new System.Func<int>(u.ReadInt32), false);
                goto done;
            }
            if ((Selector == 16404))
            {
                Arm_16404 = u.ReadEmbeddedPointer<long>(new System.Func<long>(u.ReadInt64), false);
                goto done;
            }
            if ((Selector == 16388))
            {
                Arm_16388 = u.ReadEmbeddedPointer<float>(new System.Func<float>(u.ReadFloat), false);
                goto done;
            }
            if ((Selector == 16389))
            {
                Arm_16389 = u.ReadEmbeddedPointer<double>(new System.Func<double>(u.ReadDouble), false);
                goto done;
            }
            if ((Selector == 16395))
            {
                Arm_16395 = u.ReadEmbeddedPointer<short>(new System.Func<short>(u.ReadInt16), false);
                goto done;
            }
            if ((Selector == 16394))
            {
                Arm_16394 = u.ReadEmbeddedPointer<int>(new System.Func<int>(u.ReadInt32), false);
                goto done;
            }
            if ((Selector == 16390))
            {
                Arm_16390 = u.ReadEmbeddedPointer<Struct_11>(new System.Func<Struct_11>(u.Read_11), false);
                goto done;
            }
            if ((Selector == 16391))
            {
                Arm_16391 = u.ReadEmbeddedPointer<double>(new System.Func<double>(u.ReadDouble), false);
                goto done;
            }
            if ((Selector == 16392))
            {
                Arm_16392 = u.ReadEmbeddedPointer<Struct_1>(new System.Func<Struct_1>(u.Read_1), false);
                goto done;
            }
            if ((Selector == 16397))
            {
                Arm_16397 = u.ReadEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(new System.Func<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(u.ReadInterfacePointer), false);
                goto done;
            }
            if ((Selector == 16393))
            {
                Arm_16393 = u.ReadEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(new System.Func<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer>(u.ReadInterfacePointer), false);
                goto done;
            }
            if ((Selector == 24576))
            {
                Arm_24576 = u.ReadEmbeddedPointer<Struct_2>(new System.Func<Struct_2>(u.Read_2), false);
                goto done;
            }
            if ((Selector == 16396))
            {
                Arm_16396 = u.ReadEmbeddedPointer<Struct_9>(new System.Func<Struct_9>(u.Read_9), false);
                goto done;
            }
            if ((Selector == 16))
            {
                Arm_16 = u.ReadSByte();
                goto done;
            }
            if ((Selector == 18))
            {
                Arm_18 = u.ReadInt16();
                goto done;
            }
            if ((Selector == 19))
            {
                Arm_19 = u.ReadInt32();
                goto done;
            }
            if ((Selector == 21))
            {
                Arm_21 = u.ReadInt64();
                goto done;
            }
            if ((Selector == 22))
            {
                Arm_22 = u.ReadInt32();
                goto done;
            }
            if ((Selector == 23))
            {
                Arm_23 = u.ReadInt32();
                goto done;
            }
            if ((Selector == 14))
            {
                Arm_14 = u.Read_13();
                goto done;
            }
            if ((Selector == 16398))
            {
                Arm_16398 = u.ReadEmbeddedPointer<Struct_13>(new System.Func<Struct_13>(u.Read_13), false);
                goto done;
            }
            if ((Selector == 16400))
            {
                Arm_16400 = u.ReadEmbeddedPointer<sbyte>(new System.Func<sbyte>(u.ReadSByte), false);
                goto done;
            }
            if ((Selector == 16402))
            {
                Arm_16402 = u.ReadEmbeddedPointer<short>(new System.Func<short>(u.ReadInt16), false);
                goto done;
            }
            if ((Selector == 16403))
            {
                Arm_16403 = u.ReadEmbeddedPointer<int>(new System.Func<int>(u.ReadInt32), false);
                goto done;
            }
            if ((Selector == 16405))
            {
                Arm_16405 = u.ReadEmbeddedPointer<long>(new System.Func<long>(u.ReadInt64), false);
                goto done;
            }
            if ((Selector == 16406))
            {
                Arm_16406 = u.ReadEmbeddedPointer<int>(new System.Func<int>(u.ReadInt32), false);
                goto done;
            }
            if ((Selector == 16407))
            {
                Arm_16407 = u.ReadEmbeddedPointer<int>(new System.Func<int>(u.ReadInt32), false);
                goto done;
            }
            if ((Selector == 0))
            {
                Arm_0 = u.ReadEmpty();
                goto done;
            }
            if ((Selector == 1))
            {
                Arm_1 = u.ReadEmpty();
                goto done;
            }
            throw new System.ArgumentException("No matching union selector when marshaling Union_10");
        done:
            return;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 1;
        }
        private uint Selector;
        public long Arm_20;
        public int Arm_3;
        public byte Arm_17;
        public short Arm_2;
        public float Arm_4;
        public double Arm_5;
        public short Arm_11;
        public int Arm_10;
        public Struct_11 Arm_6;
        public double Arm_7;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_1> Arm_8;
        public NtApiDotNet.Ndr.Marshal.NdrInterfacePointer Arm_13;
        public NtApiDotNet.Ndr.Marshal.NdrInterfacePointer Arm_9;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_2> Arm_8192;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_12> Arm_36;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_12> Arm_16420;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<byte> Arm_16401;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<short> Arm_16386;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<int> Arm_16387;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<long> Arm_16404;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<float> Arm_16388;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<double> Arm_16389;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<short> Arm_16395;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<int> Arm_16394;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_11> Arm_16390;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<double> Arm_16391;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_1> Arm_16392;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer> Arm_16397;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer> Arm_16393;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_2> Arm_24576;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_9> Arm_16396;
        public sbyte Arm_16;
        public short Arm_18;
        public int Arm_19;
        public long Arm_21;
        public int Arm_22;
        public int Arm_23;
        public Struct_13 Arm_14;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_13> Arm_16398;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<sbyte> Arm_16400;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<short> Arm_16402;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<int> Arm_16403;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<long> Arm_16405;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<int> Arm_16406;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<int> Arm_16407;
        public NtApiDotNet.Ndr.Marshal.NdrEmpty Arm_0;
        public NtApiDotNet.Ndr.Marshal.NdrEmpty Arm_1;
        public static Union_10 CreateDefault()
        {
            return new Union_10();
        }
        public Union_10(
                    uint Selector, 
                    long Arm_20, 
                    int Arm_3, 
                    byte Arm_17, 
                    short Arm_2, 
                    float Arm_4, 
                    double Arm_5, 
                    short Arm_11, 
                    int Arm_10, 
                    Struct_11 Arm_6, 
                    double Arm_7, 
                    System.Nullable<Struct_1> Arm_8, 
                    NtApiDotNet.Ndr.Marshal.NdrInterfacePointer Arm_13, 
                    NtApiDotNet.Ndr.Marshal.NdrInterfacePointer Arm_9, 
                    System.Nullable<Struct_2> Arm_8192, 
                    System.Nullable<Struct_12> Arm_36, 
                    System.Nullable<Struct_12> Arm_16420, 
                    System.Nullable<byte> Arm_16401, 
                    System.Nullable<short> Arm_16386, 
                    System.Nullable<int> Arm_16387, 
                    System.Nullable<long> Arm_16404, 
                    System.Nullable<float> Arm_16388, 
                    System.Nullable<double> Arm_16389, 
                    System.Nullable<short> Arm_16395, 
                    System.Nullable<int> Arm_16394, 
                    System.Nullable<Struct_11> Arm_16390, 
                    System.Nullable<double> Arm_16391, 
                    System.Nullable<Struct_1> Arm_16392, 
                    System.Nullable<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer> Arm_16397, 
                    System.Nullable<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer> Arm_16393, 
                    System.Nullable<Struct_2> Arm_24576, 
                    System.Nullable<Struct_9> Arm_16396, 
                    sbyte Arm_16, 
                    short Arm_18, 
                    int Arm_19, 
                    long Arm_21, 
                    int Arm_22, 
                    int Arm_23, 
                    Struct_13 Arm_14, 
                    System.Nullable<Struct_13> Arm_16398, 
                    System.Nullable<sbyte> Arm_16400, 
                    System.Nullable<short> Arm_16402, 
                    System.Nullable<int> Arm_16403, 
                    System.Nullable<long> Arm_16405, 
                    System.Nullable<int> Arm_16406, 
                    System.Nullable<int> Arm_16407, 
                    NtApiDotNet.Ndr.Marshal.NdrEmpty Arm_0, 
                    NtApiDotNet.Ndr.Marshal.NdrEmpty Arm_1)
        {
            this.Selector = Selector;
            this.Arm_20 = Arm_20;
            this.Arm_3 = Arm_3;
            this.Arm_17 = Arm_17;
            this.Arm_2 = Arm_2;
            this.Arm_4 = Arm_4;
            this.Arm_5 = Arm_5;
            this.Arm_11 = Arm_11;
            this.Arm_10 = Arm_10;
            this.Arm_6 = Arm_6;
            this.Arm_7 = Arm_7;
            this.Arm_8 = Arm_8;
            this.Arm_13 = Arm_13;
            this.Arm_9 = Arm_9;
            this.Arm_8192 = Arm_8192;
            this.Arm_36 = Arm_36;
            this.Arm_16420 = Arm_16420;
            this.Arm_16401 = Arm_16401;
            this.Arm_16386 = Arm_16386;
            this.Arm_16387 = Arm_16387;
            this.Arm_16404 = Arm_16404;
            this.Arm_16388 = Arm_16388;
            this.Arm_16389 = Arm_16389;
            this.Arm_16395 = Arm_16395;
            this.Arm_16394 = Arm_16394;
            this.Arm_16390 = Arm_16390;
            this.Arm_16391 = Arm_16391;
            this.Arm_16392 = Arm_16392;
            this.Arm_16397 = Arm_16397;
            this.Arm_16393 = Arm_16393;
            this.Arm_24576 = Arm_24576;
            this.Arm_16396 = Arm_16396;
            this.Arm_16 = Arm_16;
            this.Arm_18 = Arm_18;
            this.Arm_19 = Arm_19;
            this.Arm_21 = Arm_21;
            this.Arm_22 = Arm_22;
            this.Arm_23 = Arm_23;
            this.Arm_14 = Arm_14;
            this.Arm_16398 = Arm_16398;
            this.Arm_16400 = Arm_16400;
            this.Arm_16402 = Arm_16402;
            this.Arm_16403 = Arm_16403;
            this.Arm_16405 = Arm_16405;
            this.Arm_16406 = Arm_16406;
            this.Arm_16407 = Arm_16407;
            this.Arm_0 = Arm_0;
            this.Arm_1 = Arm_1;
        }
    }
    public struct Struct_11 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt64(Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt64();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public long Member0;
        public static Struct_11 CreateDefault()
        {
            return new Struct_11();
        }
        public Struct_11(long Member0)
        {
            this.Member0 = Member0;
        }
    }
    public struct Struct_12 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.WriteInterfacePointer(Member8);
            m.WriteEmbeddedPointer<byte[], long>(Member10, new System.Action<byte[], long>(m.Write_27), Member4);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.ReadInterfacePointer();
            Member10 = u.ReadEmbeddedPointer<byte[]>(new System.Func<byte[]>(u.Read_27), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public NtApiDotNet.Ndr.Marshal.NdrInterfacePointer Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<byte[]> Member10;
        public static Struct_12 CreateDefault()
        {
            return new Struct_12();
        }
        public Struct_12(int Member0, int Member4, NtApiDotNet.Ndr.Marshal.NdrInterfacePointer Member8, byte[] Member10)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.Member10 = Member10;
        }
    }
    public struct Struct_13 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt16(Member0);
            m.WriteByte(Member2);
            m.WriteByte(Member3);
            m.WriteInt32(Member4);
            m.WriteInt64(Member8);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt16();
            Member2 = u.ReadByte();
            Member3 = u.ReadByte();
            Member4 = u.ReadInt32();
            Member8 = u.ReadInt64();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public short Member0;
        public byte Member2;
        public byte Member3;
        public int Member4;
        public long Member8;
        public static Struct_13 CreateDefault()
        {
            return new Struct_13();
        }
        public Struct_13(short Member0, byte Member2, byte Member3, int Member4, long Member8)
        {
            this.Member0 = Member0;
            this.Member2 = Member2;
            this.Member3 = Member3;
            this.Member4 = Member4;
            this.Member8 = Member8;
        }
    }
    public struct Struct_14 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<Struct_12[], long>(Member8, new System.Action<Struct_12[], long>(m.Write_28), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<Struct_12[]>(new System.Func<Struct_12[]>(u.Read_28), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_12[]> Member8;
        public static Struct_14 CreateDefault()
        {
            Struct_14 ret = new Struct_14();
            ret.Member8 = new Struct_12[0];
            return ret;
        }
        public Struct_14(int Member0, Struct_12[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_15 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[], long>(Member8, new System.Action<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[], long>(m.Write_24), Member0);
            m.WriteGuid(Member10);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[]>(new System.Func<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[]>(u.Read_24), false);
            Member10 = u.ReadGuid();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[]> Member8;
        public System.Guid Member10;
        public static Struct_15 CreateDefault()
        {
            Struct_15 ret = new Struct_15();
            ret.Member8 = new NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[0];
            return ret;
        }
        public Struct_15(int Member0, NtApiDotNet.Ndr.Marshal.NdrInterfacePointer[] Member8, System.Guid Member10)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
        }
    }
    public struct Struct_17 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<byte[], long>(Member8, new System.Action<byte[], long>(m.Write_29), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<byte[]>(new System.Func<byte[]>(u.Read_29), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<byte[]> Member8;
        public static Struct_17 CreateDefault()
        {
            return new Struct_17();
        }
        public Struct_17(int Member0, byte[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_18 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<short[], long>(Member8, new System.Action<short[], long>(m.Write_30), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<short[]>(new System.Func<short[]>(u.Read_30), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<short[]> Member8;
        public static Struct_18 CreateDefault()
        {
            return new Struct_18();
        }
        public Struct_18(int Member0, short[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_19 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<int[], long>(Member8, new System.Action<int[], long>(m.Write_31), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<int[]>(new System.Func<int[]>(u.Read_31), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<int[]> Member8;
        public static Struct_19 CreateDefault()
        {
            return new Struct_19();
        }
        public Struct_19(int Member0, int[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_20 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<long[], long>(Member8, new System.Action<long[], long>(m.Write_32), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<long[]>(new System.Func<long[]>(u.Read_32), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<long[]> Member8;
        public static Struct_20 CreateDefault()
        {
            return new Struct_20();
        }
        public Struct_20(int Member0, long[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("647d4452-9f33-4a18-b2be-c5c0e920e94e", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int PlaiSrvControl(string p0, NtApiDotNet.Ndr.Marshal.NdrEnum16 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteEnum16(p1);
            _Unmarshal_Helper u = SendReceive(0, m);
            return u.ReadInt32();
        }
        public int PlaiSrvQuerySession(int p0, out int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            _Unmarshal_Helper u = SendReceive(1, m);
            p1 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int PlaiSrvGetStatus(string p0, out int p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(2, m);
            p1 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int PlaiSrvRegisterCollectorSet(out NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_0 p1, out NtApiDotNet.Ndr.Marshal.NdrUInt3264 p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_0(p1);
            _Unmarshal_Helper u = SendReceive(3, m);
            p0 = u.ReadContextHandle();
            p2 = u.ReadUInt3264();
            return u.ReadInt32();
        }
        public int PlaiSrvUpdateMetadata(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, NtApiDotNet.Ndr.Marshal.NdrUnsupported p1, int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_33(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(4, m);
            return u.ReadInt32();
        }
        public int PlaiSrvSwitchToCompiling(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(5, m);
            return u.ReadInt32();
        }
        public int PlaiSrvCloseCollectorSet(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(6, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
    }
    #endregion
}

