//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\wcncsvc.dll
// Interface ID: c100beac-d33a-4a4b-bf23-bbef4663d017
// Interface Version: 1.0



namespace rpc_c100beac_d33a_4a4b_bf23_bbef4663d017_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_1(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_2(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public byte[] Read_0()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_1()
        {
            return ReadConformantArray<byte>();
        }
        public byte[] Read_2()
        {
            return ReadConformantArray<byte>();
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("c100beac-d33a-4a4b-bf23-bbef4663d017", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int WcnSinkOpenHandle(int p0, System.Guid p1, int p2, int p3, byte[] p4, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.WriteGuid(p1);
            m.WriteInt32(p2);
            m.WriteInt32(p3);
            m.WriteReferent(p4, new System.Action<byte[], long>(m.Write_0), p3);
            _Unmarshal_Helper u = SendReceive(0, m);
            p5 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public void WcnSinkCloseHandle(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(1, m);
        }
        public int WcnSinkDeliverMessage(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, int p1, byte[] p2, System.Guid p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt32(p1);
            m.Write_1(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"), p1);
            m.WriteGuid(p3);
            _Unmarshal_Helper u = SendReceive(2, m);
            return u.ReadInt32();
        }
        // async
        public int WcnSinkAsyncGetNextAction(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, out int p1, out int p2, out byte[] p3, out System.Guid p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(3, m);
            p1 = u.ReadInt32();
            p2 = u.ReadInt32();
            p3 = u.ReadReferent<byte[]>(new System.Func<byte[]>(u.Read_2), false);
            p4 = u.ReadGuid();
            return u.ReadInt32();
        }
    }
    #endregion
}

