//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\trkwks.dll
// Interface ID: 300f3532-38cc-11d0-a3f0-0020af6b0add
// Interface Version: 1.2



namespace rpc_300f3532_38cc_11d0_a3f0_0020af6b0add_1_2
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
        public void Write_1(Struct_1 p0)
        {
            WriteStruct<Struct_1>(p0);
        }
        public void Write_2(Struct_2 p0)
        {
            WriteStruct<Struct_2>(p0);
        }
        public void Write_3(Struct_4 p0)
        {
            WriteStruct<Struct_4>(p0);
        }
        public void Write_4(Union_5 p0, long p1)
        {
            WriteUnion<Union_5>(p0, p1);
        }
        public void Write_5(Struct_6 p0)
        {
            WriteStruct<Struct_6>(p0);
        }
        public void Write_6(Struct_7 p0)
        {
            WriteStruct<Struct_7>(p0);
        }
        public void Write_7(Struct_8 p0)
        {
            WriteStruct<Struct_8>(p0);
        }
        public void Write_8(Struct_9 p0)
        {
            WriteStruct<Struct_9>(p0);
        }
        public void Write_9(Struct_10 p0)
        {
            WriteStruct<Struct_10>(p0);
        }
        public void Write_10(Struct_11 p0)
        {
            WriteStruct<Struct_11>(p0);
        }
        public void Write_11(Struct_12 p0)
        {
            WriteStruct<Struct_12>(p0);
        }
        public void Write_12(Struct_13 p0)
        {
            WriteStruct<Struct_13>(p0);
        }
        public void Write_13(Struct_14 p0)
        {
            WriteStruct<Struct_14>(p0);
        }
        public void Write_14(Struct_15 p0)
        {
            WriteStruct<Struct_15>(p0);
        }
        public void Write_15(Struct_16 p0)
        {
            WriteStruct<Struct_16>(p0);
        }
        public void Write_16(Struct_17 p0)
        {
            WriteStruct<Struct_17>(p0);
        }
        public void Write_17(Struct_18 p0)
        {
            WriteStruct<Struct_18>(p0);
        }
        public void Write_18(Union_19 p0, long p1)
        {
            WriteUnion<Union_19>(p0, p1);
        }
        public void Write_19(Struct_20 p0)
        {
            WriteStruct<Struct_20>(p0);
        }
        public void Write_20(Struct_21 p0)
        {
            WriteStruct<Struct_21>(p0);
        }
        public void Write_21(Struct_7[] p0, long p1)
        {
            WriteConformantStructArray<Struct_7>(p0, p1);
        }
        public void Write_22(string p0)
        {
            WriteFixedString(p0, 257);
        }
        public void Write_23(Struct_2[] p0, long p1)
        {
            WriteConformantStructArray<Struct_2>(p0, p1);
        }
        public void Write_24(Struct_1[] p0, long p1)
        {
            WriteConformantStructArray<Struct_1>(p0, p1);
        }
        public void Write_25(Struct_1[] p0, long p1)
        {
            WriteConformantStructArray<Struct_1>(p0, p1);
        }
        public void Write_26(Struct_2[] p0, long p1)
        {
            WriteConformantStructArray<Struct_2>(p0, p1);
        }
        public void Write_27(Struct_11[] p0, long p1)
        {
            WriteConformantStructArray<Struct_11>(p0, p1);
        }
        public void Write_28(byte[] p0)
        {
            WriteFixedByteArray(p0, 8);
        }
        public void Write_29(sbyte[] p0)
        {
            WriteFixedPrimitiveArray<sbyte>(p0, 16);
        }
        public void Write_30(Struct_1[] p0, long p1)
        {
            WriteConformantStructArray<Struct_1>(p0, p1);
        }
        public void Write_31(Struct_16[] p0, long p1)
        {
            WriteConformantStructArray<Struct_16>(p0, p1);
        }
        public void Write_32(NtApiDotNet.Ndr.Marshal.NdrPipe<Struct_17> p0)
        {
            WritePipe<Struct_17>(p0);
        }
        public void Write_33(NtApiDotNet.Ndr.Marshal.NdrPipe<Struct_16> p0)
        {
            WritePipe<Struct_16>(p0);
        }
        public void Write_34(Struct_2[] p0, long p1)
        {
            WriteConformantStructArray<Struct_2>(p0, p1);
        }
        public void Write_35(string p0, long p1)
        {
            WriteConformantVaryingString(p0, p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
        public Struct_1 Read_1()
        {
            return ReadStruct<Struct_1>();
        }
        public Struct_2 Read_2()
        {
            return ReadStruct<Struct_2>();
        }
        public Struct_4 Read_3()
        {
            return ReadStruct<Struct_4>();
        }
        public Union_5 Read_4()
        {
            return ReadStruct<Union_5>();
        }
        public Struct_6 Read_5()
        {
            return ReadStruct<Struct_6>();
        }
        public Struct_7 Read_6()
        {
            return ReadStruct<Struct_7>();
        }
        public Struct_8 Read_7()
        {
            return ReadStruct<Struct_8>();
        }
        public Struct_9 Read_8()
        {
            return ReadStruct<Struct_9>();
        }
        public Struct_10 Read_9()
        {
            return ReadStruct<Struct_10>();
        }
        public Struct_11 Read_10()
        {
            return ReadStruct<Struct_11>();
        }
        public Struct_12 Read_11()
        {
            return ReadStruct<Struct_12>();
        }
        public Struct_13 Read_12()
        {
            return ReadStruct<Struct_13>();
        }
        public Struct_14 Read_13()
        {
            return ReadStruct<Struct_14>();
        }
        public Struct_15 Read_14()
        {
            return ReadStruct<Struct_15>();
        }
        public Struct_16 Read_15()
        {
            return ReadStruct<Struct_16>();
        }
        public Struct_17 Read_16()
        {
            return ReadStruct<Struct_17>();
        }
        public Struct_18 Read_17()
        {
            return ReadStruct<Struct_18>();
        }
        public Union_19 Read_18()
        {
            return ReadStruct<Union_19>();
        }
        public Struct_20 Read_19()
        {
            return ReadStruct<Struct_20>();
        }
        public Struct_21 Read_20()
        {
            return ReadStruct<Struct_21>();
        }
        public Struct_7[] Read_21()
        {
            return ReadConformantStructArray<Struct_7>();
        }
        public string Read_22()
        {
            return ReadFixedString(257);
        }
        public Struct_2[] Read_23()
        {
            return ReadConformantStructArray<Struct_2>();
        }
        public Struct_1[] Read_24()
        {
            return ReadConformantStructArray<Struct_1>();
        }
        public Struct_1[] Read_25()
        {
            return ReadConformantStructArray<Struct_1>();
        }
        public Struct_2[] Read_26()
        {
            return ReadConformantStructArray<Struct_2>();
        }
        public Struct_11[] Read_27()
        {
            return ReadConformantStructArray<Struct_11>();
        }
        public byte[] Read_28()
        {
            return ReadFixedByteArray(8);
        }
        public sbyte[] Read_29()
        {
            return ReadFixedPrimitiveArray<sbyte>(16);
        }
        public Struct_1[] Read_30()
        {
            return ReadConformantStructArray<Struct_1>();
        }
        public Struct_16[] Read_31()
        {
            return ReadConformantStructArray<Struct_16>();
        }
        public NtApiDotNet.Ndr.Marshal.NdrPipe<Struct_17> Read_32()
        {
            return ReadPipe<Struct_17>();
        }
        public NtApiDotNet.Ndr.Marshal.NdrPipe<Struct_16> Read_33()
        {
            return ReadPipe<Struct_16>();
        }
        public Struct_2[] Read_34()
        {
            return ReadConformantStructArray<Struct_2>();
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public static Struct_0 CreateDefault()
        {
            return new Struct_0();
        }
        public Struct_0(int Member0, int Member4)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
        }
    }
    public struct Struct_1 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_2(Member0);
            m.Write_2(Member10);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_2();
            Member10 = u.Read_2();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public Struct_2 Member0;
        public Struct_2 Member10;
        public static Struct_1 CreateDefault()
        {
            return new Struct_1();
        }
        public Struct_1(Struct_2 Member0, Struct_2 Member10)
        {
            this.Member0 = Member0;
            this.Member10 = Member10;
        }
    }
    public struct Struct_2 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteGuid(Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadGuid();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public System.Guid Member0;
        public static Struct_2 CreateDefault()
        {
            return new Struct_2();
        }
        public Struct_2(System.Guid Member0)
        {
            this.Member0 = Member0;
        }
    }
    public struct Struct_4 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.Write_4(Member8, Member0);
            m.WriteEmbeddedPointer<string>(Member38, new System.Action<string>(m.WriteTerminatedString));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.Read_4();
            Member38 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public Union_5 Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member38;
        public static Struct_4 CreateDefault()
        {
            return new Struct_4();
        }
        public Struct_4(int Member0, Union_5 Member8, string Member38)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member38 = Member38;
        }
    }
    public struct Union_5 : NtApiDotNet.Ndr.Marshal.INdrNonEncapsulatedUnion
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            throw new System.NotImplementedException();
        }
        void NtApiDotNet.Ndr.Marshal.INdrNonEncapsulatedUnion.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m, long l)
        {
            Selector = ((int)(l));
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Selector);
            if ((Selector == 0))
            {
                m.Write_5(Arm_0);
                goto done;
            }
            if ((Selector == 1))
            {
                m.Write_7(Arm_1);
                goto done;
            }
            if ((Selector == 2))
            {
                m.Write_8(Arm_2);
                goto done;
            }
            if ((Selector == 3))
            {
                m.Write_9(Arm_3);
                goto done;
            }
            if ((Selector == 4))
            {
                m.Write_13(Arm_4);
                goto done;
            }
            if ((Selector == 6))
            {
                m.Write_14(Arm_6);
                goto done;
            }
            throw new System.ArgumentException("No matching union selector when marshaling Union_5");
        done:
            return;
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Selector = u.ReadInt32();
            if ((Selector == 0))
            {
                Arm_0 = u.Read_5();
                goto done;
            }
            if ((Selector == 1))
            {
                Arm_1 = u.Read_7();
                goto done;
            }
            if ((Selector == 2))
            {
                Arm_2 = u.Read_8();
                goto done;
            }
            if ((Selector == 3))
            {
                Arm_3 = u.Read_9();
                goto done;
            }
            if ((Selector == 4))
            {
                Arm_4 = u.Read_13();
                goto done;
            }
            if ((Selector == 6))
            {
                Arm_6 = u.Read_14();
                goto done;
            }
            throw new System.ArgumentException("No matching union selector when marshaling Union_5");
        done:
            return;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 1;
        }
        private int Selector;
        public Struct_6 Arm_0;
        public Struct_8 Arm_1;
        public Struct_9 Arm_2;
        public Struct_10 Arm_3;
        public Struct_14 Arm_4;
        public Struct_15 Arm_6;
        public static Union_5 CreateDefault()
        {
            return new Union_5();
        }
        public Union_5(int Selector, Struct_6 Arm_0, Struct_8 Arm_1, Struct_9 Arm_2, Struct_10 Arm_3, Struct_14 Arm_4, Struct_15 Arm_6)
        {
            this.Selector = Selector;
            this.Arm_0 = Arm_0;
            this.Arm_1 = Arm_1;
            this.Arm_2 = Arm_2;
            this.Arm_3 = Arm_3;
            this.Arm_4 = Arm_4;
            this.Arm_6 = Arm_6;
        }
    }
    public struct Struct_6 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<Struct_7[], long>(Member8, new System.Action<Struct_7[], long>(m.Write_21), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<Struct_7[]>(new System.Func<Struct_7[]>(u.Read_21), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_7[]> Member8;
        public static Struct_6 CreateDefault()
        {
            return new Struct_6();
        }
        public Struct_6(int Member0, Struct_7[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_7 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_22(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member0, "Member0"));
            m.Write_1(Member204);
            m.Write_1(Member224);
            m.WriteInt32(Member244);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_22();
            Member204 = u.Read_1();
            Member224 = u.Read_1();
            Member244 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public string Member0;
        public Struct_1 Member204;
        public Struct_1 Member224;
        public int Member244;
        public static Struct_7 CreateDefault()
        {
            Struct_7 ret = new Struct_7();
            ret.Member0 = new string('\0', 257);
            return ret;
        }
        public Struct_7(string Member0, Struct_1 Member204, Struct_1 Member224, int Member244)
        {
            this.Member0 = Member0;
            this.Member204 = Member204;
            this.Member224 = Member224;
            this.Member244 = Member244;
        }
    }
    public struct Struct_8 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.WriteInt32(Member8);
            m.WriteInt32(MemberC);
            m.WriteEmbeddedPointer<Struct_2>(Member10, new System.Action<Struct_2>(m.Write_2));
            m.WriteEmbeddedPointer<Struct_2[], long>(Member18, new System.Action<Struct_2[], long>(m.Write_23), Member0);
            m.WriteEmbeddedPointer<Struct_1[], long>(Member20, new System.Action<Struct_1[], long>(m.Write_24), Member0);
            m.WriteEmbeddedPointer<Struct_1[], long>(Member28, new System.Action<Struct_1[], long>(m.Write_24), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.ReadInt32();
            MemberC = u.ReadInt32();
            Member10 = u.ReadEmbeddedPointer<Struct_2>(new System.Func<Struct_2>(u.Read_2), false);
            Member18 = u.ReadEmbeddedPointer<Struct_2[]>(new System.Func<Struct_2[]>(u.Read_23), false);
            Member20 = u.ReadEmbeddedPointer<Struct_1[]>(new System.Func<Struct_1[]>(u.Read_24), false);
            Member28 = u.ReadEmbeddedPointer<Struct_1[]>(new System.Func<Struct_1[]>(u.Read_24), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public int Member8;
        public int MemberC;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_2> Member10;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_2[]> Member18;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_1[]> Member20;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_1[]> Member28;
        public static Struct_8 CreateDefault()
        {
            return new Struct_8();
        }
        public Struct_8(int Member0, int Member4, int Member8, int MemberC, System.Nullable<Struct_2> Member10, Struct_2[] Member18, Struct_1[] Member20, Struct_1[] Member28)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.MemberC = MemberC;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
            this.Member28 = Member28;
        }
    }
    public struct Struct_9 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<Struct_1[], long>(Member8, new System.Action<Struct_1[], long>(m.Write_25), Member0);
            m.WriteInt32(Member10);
            m.WriteEmbeddedPointer<Struct_2[], long>(Member18, new System.Action<Struct_2[], long>(m.Write_26), Member10);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<Struct_1[]>(new System.Func<Struct_1[]>(u.Read_25), false);
            Member10 = u.ReadInt32();
            Member18 = u.ReadEmbeddedPointer<Struct_2[]>(new System.Func<Struct_2[]>(u.Read_26), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_1[]> Member8;
        public int Member10;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_2[]> Member18;
        public static Struct_9 CreateDefault()
        {
            return new Struct_9();
        }
        public Struct_9(int Member0, Struct_1[] Member8, int Member10, Struct_2[] Member18)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
        }
    }
    public struct Struct_10 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<Struct_11[], long>(Member8, new System.Action<Struct_11[], long>(m.Write_27), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<Struct_11[]>(new System.Func<Struct_11[]>(u.Read_27), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_11[]> Member8;
        public static Struct_10 CreateDefault()
        {
            return new Struct_10();
        }
        public Struct_10(int Member0, Struct_11[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_11 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.Write_2(Member8);
            m.Write_11(Member18);
            m.Write_11(Member20);
            m.WriteInt32(Member28);
            m.Write_0(Member2C);
            m.Write_12(Member34);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.Read_2();
            Member18 = u.Read_11();
            Member20 = u.Read_11();
            Member28 = u.ReadInt32();
            Member2C = u.Read_0();
            Member34 = u.Read_12();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public Struct_2 Member8;
        public Struct_12 Member18;
        public Struct_12 Member20;
        public int Member28;
        public Struct_0 Member2C;
        public Struct_13 Member34;
        public static Struct_11 CreateDefault()
        {
            return new Struct_11();
        }
        public Struct_11(int Member0, int Member4, Struct_2 Member8, Struct_12 Member18, Struct_12 Member20, int Member28, Struct_0 Member2C, Struct_13 Member34)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.Member18 = Member18;
            this.Member20 = Member20;
            this.Member28 = Member28;
            this.Member2C = Member2C;
            this.Member34 = Member34;
        }
    }
    public struct Struct_12 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_28(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member0, "Member0"));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_28();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 1;
        }
        public byte[] Member0;
        public static Struct_12 CreateDefault()
        {
            Struct_12 ret = new Struct_12();
            ret.Member0 = new byte[8];
            return ret;
        }
        public Struct_12(byte[] Member0)
        {
            this.Member0 = Member0;
        }
    }
    public struct Struct_13 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_29(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member0, "Member0"));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_29();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 1;
        }
        public sbyte[] Member0;
        public static Struct_13 CreateDefault()
        {
            Struct_13 ret = new Struct_13();
            ret.Member0 = new sbyte[16];
            return ret;
        }
        public Struct_13(sbyte[] Member0)
        {
            this.Member0 = Member0;
        }
    }
    public struct Struct_14 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<Struct_1[], long>(Member8, new System.Action<Struct_1[], long>(m.Write_30), Member0);
            m.WriteInt32(Member10);
            m.WriteEmbeddedPointer<Struct_2[], long>(Member18, new System.Action<Struct_2[], long>(m.Write_26), Member10);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<Struct_1[]>(new System.Func<Struct_1[]>(u.Read_30), false);
            Member10 = u.ReadInt32();
            Member18 = u.ReadEmbeddedPointer<Struct_2[]>(new System.Func<Struct_2[]>(u.Read_26), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_1[]> Member8;
        public int Member10;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_2[]> Member18;
        public static Struct_14 CreateDefault()
        {
            return new Struct_14();
        }
        public Struct_14(int Member0, Struct_1[] Member8, int Member10, Struct_2[] Member18)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
        }
    }
    public struct Struct_15 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<Struct_16[], long>(Member8, new System.Action<Struct_16[], long>(m.Write_31), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<Struct_16[]>(new System.Func<Struct_16[]>(u.Read_31), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_16[]> Member8;
        public static Struct_15 CreateDefault()
        {
            return new Struct_15();
        }
        public Struct_15(int Member0, Struct_16[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_16 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_1(Member0);
            m.Write_1(Member20);
            m.Write_12(Member40);
            m.WriteInt32(Member50);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_1();
            Member20 = u.Read_1();
            Member40 = u.Read_12();
            Member50 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public Struct_1 Member0;
        public Struct_1 Member20;
        public Struct_13 Member40;
        public int Member50;
        public static Struct_16 CreateDefault()
        {
            return new Struct_16();
        }
        public Struct_16(Struct_1 Member0, Struct_1 Member20, Struct_13 Member40, int Member50)
        {
            this.Member0 = Member0;
            this.Member20 = Member20;
            this.Member40 = Member40;
            this.Member50 = Member50;
        }
    }
    public struct Struct_17 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.Write_2(Member4);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.Read_2();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public Struct_2 Member4;
        public static Struct_17 CreateDefault()
        {
            return new Struct_17();
        }
        public Struct_17(int Member0, Struct_2 Member4)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
        }
    }
    public struct Struct_18 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.Write_18(Member8, Member0);
            m.WriteEmbeddedPointer<string>(MemberD0, new System.Action<string>(m.WriteTerminatedString));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.Read_18();
            MemberD0 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public Union_19 Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> MemberD0;
        public static Struct_18 CreateDefault()
        {
            return new Struct_18();
        }
        public Struct_18(int Member0, int Member4, Union_19 Member8, string MemberD0)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.MemberD0 = MemberD0;
        }
    }
    public struct Union_19 : NtApiDotNet.Ndr.Marshal.INdrNonEncapsulatedUnion
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            throw new System.NotImplementedException();
        }
        void NtApiDotNet.Ndr.Marshal.INdrNonEncapsulatedUnion.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m, long l)
        {
            Selector = ((int)(l));
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Selector);
            if ((Selector == 0))
            {
                m.Write_5(Arm_0);
                goto done;
            }
            if ((Selector == 1))
            {
                m.Write_7(Arm_1);
                goto done;
            }
            if ((Selector == 2))
            {
                m.Write_8(Arm_2);
                goto done;
            }
            if ((Selector == 3))
            {
                m.Write_9(Arm_3);
                goto done;
            }
            if ((Selector == 4))
            {
                m.Write_13(Arm_4);
                goto done;
            }
            if ((Selector == 5))
            {
                m.Write_19(Arm_5);
                goto done;
            }
            if ((Selector == 6))
            {
                m.Write_14(Arm_6);
                goto done;
            }
            if ((Selector == 7))
            {
                m.Write_0(Arm_7);
                goto done;
            }
            if ((Selector == 8))
            {
                m.WriteInt32(Arm_8);
                goto done;
            }
            throw new System.ArgumentException("No matching union selector when marshaling Union_19");
        done:
            return;
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Selector = u.ReadInt32();
            if ((Selector == 0))
            {
                Arm_0 = u.Read_5();
                goto done;
            }
            if ((Selector == 1))
            {
                Arm_1 = u.Read_7();
                goto done;
            }
            if ((Selector == 2))
            {
                Arm_2 = u.Read_8();
                goto done;
            }
            if ((Selector == 3))
            {
                Arm_3 = u.Read_9();
                goto done;
            }
            if ((Selector == 4))
            {
                Arm_4 = u.Read_13();
                goto done;
            }
            if ((Selector == 5))
            {
                Arm_5 = u.Read_19();
                goto done;
            }
            if ((Selector == 6))
            {
                Arm_6 = u.Read_14();
                goto done;
            }
            if ((Selector == 7))
            {
                Arm_7 = u.Read_0();
                goto done;
            }
            if ((Selector == 8))
            {
                Arm_8 = u.ReadInt32();
                goto done;
            }
            throw new System.ArgumentException("No matching union selector when marshaling Union_19");
        done:
            return;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 1;
        }
        private int Selector;
        public Struct_6 Arm_0;
        public Struct_8 Arm_1;
        public Struct_9 Arm_2;
        public Struct_10 Arm_3;
        public Struct_14 Arm_4;
        public Struct_20 Arm_5;
        public Struct_15 Arm_6;
        public Struct_0 Arm_7;
        public int Arm_8;
        public static Union_19 CreateDefault()
        {
            return new Union_19();
        }
        public Union_19(int Selector, Struct_6 Arm_0, Struct_8 Arm_1, Struct_9 Arm_2, Struct_10 Arm_3, Struct_14 Arm_4, Struct_20 Arm_5, Struct_15 Arm_6, Struct_0 Arm_7, int Arm_8)
        {
            this.Selector = Selector;
            this.Arm_0 = Arm_0;
            this.Arm_1 = Arm_1;
            this.Arm_2 = Arm_2;
            this.Arm_3 = Arm_3;
            this.Arm_4 = Arm_4;
            this.Arm_5 = Arm_5;
            this.Arm_6 = Arm_6;
            this.Arm_7 = Arm_7;
            this.Arm_8 = Arm_8;
        }
    }
    public struct Struct_20 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.WriteInt32(Member8);
            m.WriteInt32(MemberC);
            m.WriteInt32(Member10);
            m.WriteInt32(Member14);
            m.WriteInt32(Member18);
            m.WriteInt32(Member1C);
            m.WriteInt32(Member20);
            m.WriteInt32(Member24);
            m.WriteInt32(Member28);
            m.WriteInt32(Member2C);
            m.WriteInt32(Member30);
            m.WriteInt32(Member34);
            m.WriteInt32(Member38);
            m.WriteInt32(Member3C);
            m.WriteInt32(Member40);
            m.WriteInt32(Member44);
            m.WriteInt32(Member48);
            m.WriteInt32(Member4C);
            m.WriteInt32(Member50);
            m.WriteInt32(Member54);
            m.WriteInt32(Member58);
            m.WriteInt32(Member5C);
            m.WriteInt32(Member60);
            m.WriteInt32(Member64);
            m.Write_0(Member68);
            m.WriteInt32(Member70);
            m.WriteInt32(Member74);
            m.WriteInt32(Member78);
            m.WriteInt32(Member7C);
            m.WriteInt32(Member80);
            m.Write_0(Member84);
            m.WriteInt32(Member8C);
            m.Write_0(Member90);
            m.Write_0(Member98);
            m.WriteInt32(MemberA0);
            m.WriteInt32(MemberA4);
            m.WriteInt32(MemberA8);
            m.WriteInt32(MemberAC);
            m.WriteInt32(MemberB0);
            m.WriteInt16(MemberB4);
            m.WriteInt16(MemberB6);
            m.WriteInt16(MemberB8);
            m.WriteInt16(MemberBA);
            m.Write_20(MemberBC);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.ReadInt32();
            MemberC = u.ReadInt32();
            Member10 = u.ReadInt32();
            Member14 = u.ReadInt32();
            Member18 = u.ReadInt32();
            Member1C = u.ReadInt32();
            Member20 = u.ReadInt32();
            Member24 = u.ReadInt32();
            Member28 = u.ReadInt32();
            Member2C = u.ReadInt32();
            Member30 = u.ReadInt32();
            Member34 = u.ReadInt32();
            Member38 = u.ReadInt32();
            Member3C = u.ReadInt32();
            Member40 = u.ReadInt32();
            Member44 = u.ReadInt32();
            Member48 = u.ReadInt32();
            Member4C = u.ReadInt32();
            Member50 = u.ReadInt32();
            Member54 = u.ReadInt32();
            Member58 = u.ReadInt32();
            Member5C = u.ReadInt32();
            Member60 = u.ReadInt32();
            Member64 = u.ReadInt32();
            Member68 = u.Read_0();
            Member70 = u.ReadInt32();
            Member74 = u.ReadInt32();
            Member78 = u.ReadInt32();
            Member7C = u.ReadInt32();
            Member80 = u.ReadInt32();
            Member84 = u.Read_0();
            Member8C = u.ReadInt32();
            Member90 = u.Read_0();
            Member98 = u.Read_0();
            MemberA0 = u.ReadInt32();
            MemberA4 = u.ReadInt32();
            MemberA8 = u.ReadInt32();
            MemberAC = u.ReadInt32();
            MemberB0 = u.ReadInt32();
            MemberB4 = u.ReadInt16();
            MemberB6 = u.ReadInt16();
            MemberB8 = u.ReadInt16();
            MemberBA = u.ReadInt16();
            MemberBC = u.Read_20();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public int Member8;
        public int MemberC;
        public int Member10;
        public int Member14;
        public int Member18;
        public int Member1C;
        public int Member20;
        public int Member24;
        public int Member28;
        public int Member2C;
        public int Member30;
        public int Member34;
        public int Member38;
        public int Member3C;
        public int Member40;
        public int Member44;
        public int Member48;
        public int Member4C;
        public int Member50;
        public int Member54;
        public int Member58;
        public int Member5C;
        public int Member60;
        public int Member64;
        public Struct_0 Member68;
        public int Member70;
        public int Member74;
        public int Member78;
        public int Member7C;
        public int Member80;
        public Struct_0 Member84;
        public int Member8C;
        public Struct_0 Member90;
        public Struct_0 Member98;
        public int MemberA0;
        public int MemberA4;
        public int MemberA8;
        public int MemberAC;
        public int MemberB0;
        public short MemberB4;
        public short MemberB6;
        public short MemberB8;
        public short MemberBA;
        public Struct_21 MemberBC;
        public static Struct_20 CreateDefault()
        {
            return new Struct_20();
        }
        public Struct_20(
                    int Member0, 
                    int Member4, 
                    int Member8, 
                    int MemberC, 
                    int Member10, 
                    int Member14, 
                    int Member18, 
                    int Member1C, 
                    int Member20, 
                    int Member24, 
                    int Member28, 
                    int Member2C, 
                    int Member30, 
                    int Member34, 
                    int Member38, 
                    int Member3C, 
                    int Member40, 
                    int Member44, 
                    int Member48, 
                    int Member4C, 
                    int Member50, 
                    int Member54, 
                    int Member58, 
                    int Member5C, 
                    int Member60, 
                    int Member64, 
                    Struct_0 Member68, 
                    int Member70, 
                    int Member74, 
                    int Member78, 
                    int Member7C, 
                    int Member80, 
                    Struct_0 Member84, 
                    int Member8C, 
                    Struct_0 Member90, 
                    Struct_0 Member98, 
                    int MemberA0, 
                    int MemberA4, 
                    int MemberA8, 
                    int MemberAC, 
                    int MemberB0, 
                    short MemberB4, 
                    short MemberB6, 
                    short MemberB8, 
                    short MemberBA, 
                    Struct_21 MemberBC)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.MemberC = MemberC;
            this.Member10 = Member10;
            this.Member14 = Member14;
            this.Member18 = Member18;
            this.Member1C = Member1C;
            this.Member20 = Member20;
            this.Member24 = Member24;
            this.Member28 = Member28;
            this.Member2C = Member2C;
            this.Member30 = Member30;
            this.Member34 = Member34;
            this.Member38 = Member38;
            this.Member3C = Member3C;
            this.Member40 = Member40;
            this.Member44 = Member44;
            this.Member48 = Member48;
            this.Member4C = Member4C;
            this.Member50 = Member50;
            this.Member54 = Member54;
            this.Member58 = Member58;
            this.Member5C = Member5C;
            this.Member60 = Member60;
            this.Member64 = Member64;
            this.Member68 = Member68;
            this.Member70 = Member70;
            this.Member74 = Member74;
            this.Member78 = Member78;
            this.Member7C = Member7C;
            this.Member80 = Member80;
            this.Member84 = Member84;
            this.Member8C = Member8C;
            this.Member90 = Member90;
            this.Member98 = Member98;
            this.MemberA0 = MemberA0;
            this.MemberA4 = MemberA4;
            this.MemberA8 = MemberA8;
            this.MemberAC = MemberAC;
            this.MemberB0 = MemberB0;
            this.MemberB4 = MemberB4;
            this.MemberB6 = MemberB6;
            this.MemberB8 = MemberB8;
            this.MemberBA = MemberBA;
            this.MemberBC = MemberBC;
        }
    }
    public struct Struct_21 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.WriteInt32(Member8);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public int Member8;
        public static Struct_21 CreateDefault()
        {
            return new Struct_21();
        }
        public Struct_21(int Member0, int Member4, int Member8)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("300f3532-38cc-11d0-a3f0-0020af6b0add", 1, 2)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int Stubold_LnkMendLink(Struct_0 p0, int p1, Struct_1 p2, Struct_1 p3, out Struct_1 p4, out string p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_0(p0);
            m.WriteInt32(p1);
            m.Write_1(p2);
            m.Write_1(p3);
            _Unmarshal_Helper u = SendReceive(0, m);
            p4 = u.Read_1();
            p5 = u.ReadVaryingString();
            return u.ReadInt32();
        }
        public int Stubold_LnkSearchMachine(int p0, Struct_1 p1, out Struct_1 p2, out string p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.Write_1(p1);
            _Unmarshal_Helper u = SendReceive(1, m);
            p2 = u.Read_1();
            p3 = u.ReadVaryingString();
            return u.ReadInt32();
        }
        public int Stubold_LnkSearchMachine_2(ref Struct_4 p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_3(p0);
            _Unmarshal_Helper u = SendReceive(2, m);
            p0 = u.Read_3();
            return u.ReadInt32();
        }
        public int StubLnkSetVolumeId(int p0, Struct_2 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.Write_2(p1);
            _Unmarshal_Helper u = SendReceive(3, m);
            return u.ReadInt32();
        }
        public int Stubold_LnkSearchMachine_4()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(4, m);
            return u.ReadInt32();
        }
        public int Stubold_LnkSearchMachine_5(Struct_2 p0, int p1, out NtApiDotNet.Ndr.Marshal.NdrPipe<Struct_17> p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_2(p0);
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(5, m);
            p2 = u.Read_32();
            return u.ReadInt32();
        }
        public int Stubold_LnkSearchMachine_6(Struct_1 p0, int p1, out NtApiDotNet.Ndr.Marshal.NdrPipe<Struct_16> p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_1(p0);
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(6, m);
            p2 = u.Read_33();
            return u.ReadInt32();
        }
        public int Stubold_LnkSearchMachine_7(int p0, Struct_2[] p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.Write_34(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"), p0);
            _Unmarshal_Helper u = SendReceive(7, m);
            return u.ReadInt32();
        }
        public int StubLnkOnRestore()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(8, m);
            return u.ReadInt32();
        }
        // async
        public int StubLnkMendLink(Struct_0 p0, int p1, Struct_1 p2, Struct_1 p3, Struct_13 p4, out Struct_1 p5, out Struct_13 p6, out string p7)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_0(p0);
            m.WriteInt32(p1);
            m.Write_1(p2);
            m.Write_1(p3);
            m.Write_12(p4);
            _Unmarshal_Helper u = SendReceive(9, m);
            p5 = u.Read_1();
            p6 = u.Read_12();
            p7 = u.ReadVaryingString();
            return u.ReadInt32();
        }
        public int Stubold_LnkSearchMachine_10(int p0, Struct_1 p1, out Struct_1 p2, out Struct_13 p3, out string p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.Write_1(p1);
            _Unmarshal_Helper u = SendReceive(10, m);
            p2 = u.Read_1();
            p3 = u.Read_12();
            p4 = u.ReadVaryingString();
            return u.ReadInt32();
        }
        public int Stubold_LnkSearchMachine_11(ref Struct_18 p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_17(p0);
            _Unmarshal_Helper u = SendReceive(11, m);
            p0 = u.Read_17();
            return u.ReadInt32();
        }
        public int StubLnkSearchMachine(int p0, Struct_1 p1, Struct_1 p2, out Struct_1 p3, out Struct_1 p4, out Struct_13 p5, out string p6)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.Write_1(p1);
            m.Write_1(p2);
            _Unmarshal_Helper u = SendReceive(12, m);
            p3 = u.Read_1();
            p4 = u.Read_1();
            p5 = u.Read_12();
            p6 = u.ReadConformantVaryingString();
            return u.ReadInt32();
        }
    }
    #endregion
}

