//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\wininet.dll
// Interface ID: 7856fb07-7efe-4029-a4cb-4848641c40ff
// Interface Version: 1.0



namespace rpc_7856fb07_7efe_4029_a4cb_4848641c40ff_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
        public void Write_1(Struct_1 p0)
        {
            WriteStruct<Struct_1>(p0);
        }
        public void Write_2(Struct_2 p0)
        {
            WriteStruct<Struct_2>(p0);
        }
        public void Write_3(Struct_3 p0)
        {
            WriteStruct<Struct_3>(p0);
        }
        public void Write_4(Struct_4 p0)
        {
            WriteStruct<Struct_4>(p0);
        }
        public void Write_5(Struct_5 p0)
        {
            WriteStruct<Struct_5>(p0);
        }
        public void Write_6(Struct_6 p0)
        {
            WriteStruct<Struct_6>(p0);
        }
        public void Write_7(Union_7 p0, long p1)
        {
            WriteUnion<Union_7>(p0, p1);
        }
        public void Write_8(Struct_8 p0)
        {
            WriteStruct<Struct_8>(p0);
        }
        public void Write_9(Struct_9 p0)
        {
            WriteStruct<Struct_9>(p0);
        }
        public void Write_10(Struct_10 p0)
        {
            WriteStruct<Struct_10>(p0);
        }
        public void Write_11(Struct_11 p0)
        {
            WriteStruct<Struct_11>(p0);
        }
        public void Write_12(Struct_12 p0)
        {
            WriteStruct<Struct_12>(p0);
        }
        public void Write_13(Struct_13 p0)
        {
            WriteStruct<Struct_13>(p0);
        }
        public void Write_14(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_15(char[] p0, long p1)
        {
            WriteConformantArray<char>(p0, p1);
        }
        public void Write_16(char[] p0, long p1)
        {
            WriteConformantArray<char>(p0, p1);
        }
        public void Write_17(Struct_2[] p0, long p1)
        {
            WriteConformantStructArray<Struct_2>(p0, p1);
        }
        public void Write_18(Struct_4[] p0, long p1)
        {
            WriteConformantStructArray<Struct_4>(p0, p1);
        }
        public void Write_19(char[] p0, long p1)
        {
            WriteConformantArray<char>(p0, p1);
        }
        public void Write_20(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_21(int[] p0, long p1)
        {
            WriteConformantArray<int>(p0, p1);
        }
        public void Write_22(sbyte[] p0)
        {
            WriteFixedPrimitiveArray<sbyte>(p0, 6);
        }
        public void Write_23(char[] p0, long p1)
        {
            WriteConformantArray<char>(p0, p1);
        }
        public void Write_24(char[] p0, long p1)
        {
            WriteConformantArray<char>(p0, p1);
        }
        public void Write_25(char[] p0, long p1)
        {
            WriteConformantArray<char>(p0, p1);
        }
        public void Write_26(Struct_3[] p0, long p1)
        {
            WriteConformantStructArray<Struct_3>(p0, p1);
        }
        public void Write_27(char[] p0, long p1)
        {
            WriteConformantArray<char>(p0, p1);
        }
        public void Write_28(char[] p0, long p1)
        {
            WriteConformantArray<char>(p0, p1);
        }
        public void Write_29(Struct_11[] p0, long p1)
        {
            WriteConformantStructArray<Struct_11>(p0, p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
        public Struct_1 Read_1()
        {
            return ReadStruct<Struct_1>();
        }
        public Struct_2 Read_2()
        {
            return ReadStruct<Struct_2>();
        }
        public Struct_3 Read_3()
        {
            return ReadStruct<Struct_3>();
        }
        public Struct_4 Read_4()
        {
            return ReadStruct<Struct_4>();
        }
        public Struct_5 Read_5()
        {
            return ReadStruct<Struct_5>();
        }
        public Struct_6 Read_6()
        {
            return ReadStruct<Struct_6>();
        }
        public Union_7 Read_7()
        {
            return ReadStruct<Union_7>();
        }
        public Struct_8 Read_8()
        {
            return ReadStruct<Struct_8>();
        }
        public Struct_9 Read_9()
        {
            return ReadStruct<Struct_9>();
        }
        public Struct_10 Read_10()
        {
            return ReadStruct<Struct_10>();
        }
        public Struct_11 Read_11()
        {
            return ReadStruct<Struct_11>();
        }
        public Struct_12 Read_12()
        {
            return ReadStruct<Struct_12>();
        }
        public Struct_13 Read_13()
        {
            return ReadStruct<Struct_13>();
        }
        public byte[] Read_14()
        {
            return ReadConformantArray<byte>();
        }
        public char[] Read_15()
        {
            return ReadConformantArray<char>();
        }
        public char[] Read_16()
        {
            return ReadConformantArray<char>();
        }
        public Struct_2[] Read_17()
        {
            return ReadConformantStructArray<Struct_2>();
        }
        public Struct_4[] Read_18()
        {
            return ReadConformantStructArray<Struct_4>();
        }
        public char[] Read_19()
        {
            return ReadConformantArray<char>();
        }
        public byte[] Read_20()
        {
            return ReadConformantArray<byte>();
        }
        public int[] Read_21()
        {
            return ReadConformantArray<int>();
        }
        public sbyte[] Read_22()
        {
            return ReadFixedPrimitiveArray<sbyte>(6);
        }
        public char[] Read_23()
        {
            return ReadConformantArray<char>();
        }
        public char[] Read_24()
        {
            return ReadConformantArray<char>();
        }
        public char[] Read_25()
        {
            return ReadConformantArray<char>();
        }
        public Struct_3[] Read_26()
        {
            return ReadConformantStructArray<Struct_3>();
        }
        public char[] Read_27()
        {
            return ReadConformantArray<char>();
        }
        public char[] Read_28()
        {
            return ReadConformantArray<char>();
        }
        public Struct_11[] Read_29()
        {
            return ReadConformantStructArray<Struct_11>();
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteSByte(Member0);
            m.WriteInt32(Member4);
            m.WriteEmbeddedPointer<byte[], long>(Member8, new System.Action<byte[], long>(m.Write_14), Member4);
            m.WriteInt32(Member10);
            m.WriteEmbeddedPointer<char[], long>(Member18, new System.Action<char[], long>(m.Write_15), Member10);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadSByte();
            Member4 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<byte[]>(new System.Func<byte[]>(u.Read_14), false);
            Member10 = u.ReadInt32();
            Member18 = u.ReadEmbeddedPointer<char[]>(new System.Func<char[]>(u.Read_15), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public sbyte Member0;
        public int Member4;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<byte[]> Member8;
        public int Member10;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<char[]> Member18;
        public static Struct_0 CreateDefault()
        {
            Struct_0 ret = new Struct_0();
            ret.Member8 = new byte[0];
            return ret;
        }
        public Struct_0(sbyte Member0, int Member4, byte[] Member8, int Member10, char[] Member18)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
        }
    }
    public struct Struct_1 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.WriteEmbeddedPointer<char[], long>(Member8, new System.Action<char[], long>(m.Write_16), Member4);
            m.WriteInt64(Member10);
            m.WriteInt64(Member18);
            m.WriteInt32(Member20);
            m.WriteEmbeddedPointer<Struct_2[], long>(Member28, new System.Action<Struct_2[], long>(m.Write_17), Member20);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<char[]>(new System.Func<char[]>(u.Read_16), false);
            Member10 = u.ReadInt64();
            Member18 = u.ReadInt64();
            Member20 = u.ReadInt32();
            Member28 = u.ReadEmbeddedPointer<Struct_2[]>(new System.Func<Struct_2[]>(u.Read_17), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public int Member0;
        public int Member4;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<char[]> Member8;
        public long Member10;
        public long Member18;
        public int Member20;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_2[]> Member28;
        public static Struct_1 CreateDefault()
        {
            return new Struct_1();
        }
        public Struct_1(int Member0, int Member4, char[] Member8, long Member10, long Member18, int Member20, Struct_2[] Member28)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
            this.Member28 = Member28;
        }
    }
    public struct Struct_2 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt64(Member0);
            m.Write_3(Member8);
            m.Write_3(Member18);
            m.WriteSByte(Member28);
            m.WriteInt32(Member2C);
            m.WriteEmbeddedPointer<Struct_4[], long>(Member30, new System.Action<Struct_4[], long>(m.Write_18), Member2C);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt64();
            Member8 = u.Read_3();
            Member18 = u.Read_3();
            Member28 = u.ReadSByte();
            Member2C = u.ReadInt32();
            Member30 = u.ReadEmbeddedPointer<Struct_4[]>(new System.Func<Struct_4[]>(u.Read_18), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public long Member0;
        public Struct_3 Member8;
        public Struct_3 Member18;
        public sbyte Member28;
        public int Member2C;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_4[]> Member30;
        public static Struct_2 CreateDefault()
        {
            return new Struct_2();
        }
        public Struct_2(long Member0, Struct_3 Member8, Struct_3 Member18, sbyte Member28, int Member2C, Struct_4[] Member30)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member18 = Member18;
            this.Member28 = Member28;
            this.Member2C = Member2C;
            this.Member30 = Member30;
        }
    }
    public struct Struct_3 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<char[], long>(Member8, new System.Action<char[], long>(m.Write_19), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<char[]>(new System.Func<char[]>(u.Read_19), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<char[]> Member8;
        public static Struct_3 CreateDefault()
        {
            return new Struct_3();
        }
        public Struct_3(int Member0, char[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_4 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt64(Member0);
            m.Write_3(Member8);
            m.Write_3(Member18);
            m.WriteSByte(Member28);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt64();
            Member8 = u.Read_3();
            Member18 = u.Read_3();
            Member28 = u.ReadSByte();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public long Member0;
        public Struct_3 Member8;
        public Struct_3 Member18;
        public sbyte Member28;
        public static Struct_4 CreateDefault()
        {
            return new Struct_4();
        }
        public Struct_4(long Member0, Struct_3 Member8, Struct_3 Member18, sbyte Member28)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member18 = Member18;
            this.Member28 = Member28;
        }
    }
    public struct Struct_5 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<byte[], long>(Member8, new System.Action<byte[], long>(m.Write_20), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<byte[]>(new System.Func<byte[]>(u.Read_20), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<byte[]> Member8;
        public static Struct_5 CreateDefault()
        {
            return new Struct_5();
        }
        public Struct_5(int Member0, byte[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_6 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEnum16(Member0);
            m.Write_7(Member8, Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEnum16();
            Member8 = u.Read_7();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEnum16 Member0;
        public Union_7 Member8;
        public static Struct_6 CreateDefault()
        {
            return new Struct_6();
        }
        public Struct_6(NtApiDotNet.Ndr.Marshal.NdrEnum16 Member0, Union_7 Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Union_7 : NtApiDotNet.Ndr.Marshal.INdrNonEncapsulatedUnion
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            throw new System.NotImplementedException();
        }
        void NtApiDotNet.Ndr.Marshal.INdrNonEncapsulatedUnion.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m, long l)
        {
            Selector = ((ushort)(l));
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteUInt16(Selector);
            if ((Selector == 1))
            {
                m.WriteInt32(Arm_1);
                goto done;
            }
            if ((Selector == 2))
            {
                m.WriteDouble(Arm_2);
                goto done;
            }
            if ((Selector == 3))
            {
                m.WriteDouble(Arm_3);
                goto done;
            }
            if ((Selector == 4))
            {
                m.Write_3(Arm_4);
                goto done;
            }
            if ((Selector == 0))
            {
                m.WriteEmpty(Arm_0);
                goto done;
            }
            throw new System.ArgumentException("No matching union selector when marshaling Union_7");
        done:
            return;
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Selector = u.ReadUInt16();
            if ((Selector == 1))
            {
                Arm_1 = u.ReadInt32();
                goto done;
            }
            if ((Selector == 2))
            {
                Arm_2 = u.ReadDouble();
                goto done;
            }
            if ((Selector == 3))
            {
                Arm_3 = u.ReadDouble();
                goto done;
            }
            if ((Selector == 4))
            {
                Arm_4 = u.Read_3();
                goto done;
            }
            if ((Selector == 0))
            {
                Arm_0 = u.ReadEmpty();
                goto done;
            }
            throw new System.ArgumentException("No matching union selector when marshaling Union_7");
        done:
            return;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 1;
        }
        private ushort Selector;
        public int Arm_1;
        public double Arm_2;
        public double Arm_3;
        public Struct_3 Arm_4;
        public NtApiDotNet.Ndr.Marshal.NdrEmpty Arm_0;
        public static Union_7 CreateDefault()
        {
            return new Union_7();
        }
        public Union_7(ushort Selector, int Arm_1, double Arm_2, double Arm_3, Struct_3 Arm_4, NtApiDotNet.Ndr.Marshal.NdrEmpty Arm_0)
        {
            this.Selector = Selector;
            this.Arm_1 = Arm_1;
            this.Arm_2 = Arm_2;
            this.Arm_3 = Arm_3;
            this.Arm_4 = Arm_4;
            this.Arm_0 = Arm_0;
        }
    }
    public struct Struct_8 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_5(Member0);
            m.WriteEmbeddedPointer<Struct_6>(Member10, new System.Action<Struct_6>(m.Write_6));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_5();
            Member10 = u.ReadEmbeddedPointer<Struct_6>(new System.Func<Struct_6>(u.Read_6), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public Struct_5 Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<Struct_6> Member10;
        public static Struct_8 CreateDefault()
        {
            return new Struct_8();
        }
        public Struct_8(Struct_5 Member0, System.Nullable<Struct_6> Member10)
        {
            this.Member0 = Member0;
            this.Member10 = Member10;
        }
    }
    public struct Struct_9 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_6(Member0);
            m.Write_6(Member18);
            m.WriteSByte(Member30);
            m.WriteSByte(Member31);
            m.WriteSByte(Member32);
            m.WriteSByte(Member33);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_6();
            Member18 = u.Read_6();
            Member30 = u.ReadSByte();
            Member31 = u.ReadSByte();
            Member32 = u.ReadSByte();
            Member33 = u.ReadSByte();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public Struct_6 Member0;
        public Struct_6 Member18;
        public sbyte Member30;
        public sbyte Member31;
        public sbyte Member32;
        public sbyte Member33;
        public static Struct_9 CreateDefault()
        {
            return new Struct_9();
        }
        public Struct_9(Struct_6 Member0, Struct_6 Member18, sbyte Member30, sbyte Member31, sbyte Member32, sbyte Member33)
        {
            this.Member0 = Member0;
            this.Member18 = Member18;
            this.Member30 = Member30;
            this.Member31 = Member31;
            this.Member32 = Member32;
            this.Member33 = Member33;
        }
    }
    public struct Struct_10 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteSByte(Member0);
            m.Write_6(Member8);
            m.Write_6(Member20);
            m.Write_8(Member38);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadSByte();
            Member8 = u.Read_6();
            Member20 = u.Read_6();
            Member38 = u.Read_8();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public sbyte Member0;
        public Struct_6 Member8;
        public Struct_6 Member20;
        public Struct_8 Member38;
        public static Struct_10 CreateDefault()
        {
            return new Struct_10();
        }
        public Struct_10(sbyte Member0, Struct_6 Member8, Struct_6 Member20, Struct_8 Member38)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member20 = Member20;
            this.Member38 = Member38;
        }
    }
    public struct Struct_11 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_3(Member0);
            m.WriteInt64(Member10);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_3();
            Member10 = u.ReadInt64();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public Struct_3 Member0;
        public long Member10;
        public static Struct_11 CreateDefault()
        {
            return new Struct_11();
        }
        public Struct_11(Struct_3 Member0, long Member10)
        {
            this.Member0 = Member0;
            this.Member10 = Member10;
        }
    }
    public struct Struct_12 : NtApiDotNet.Ndr.Marshal.INdrConformantStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteByte(Member0);
            m.WriteByte(Member1);
            m.Write_13(Member2);
            m.Write_21(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member8, "Member8"), Member1);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadByte();
            Member1 = u.ReadByte();
            Member2 = u.Read_13();
            Member8 = u.Read_21();
        }
        int NtApiDotNet.Ndr.Marshal.INdrConformantStructure.GetConformantDimensions()
        {
            return 1;
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public byte Member0;
        public byte Member1;
        public Struct_13 Member2;
        public int[] Member8;
        public static Struct_12 CreateDefault()
        {
            Struct_12 ret = new Struct_12();
            ret.Member8 = new int[0];
            return ret;
        }
        public Struct_12(byte Member0, byte Member1, Struct_13 Member2, int[] Member8)
        {
            this.Member0 = Member0;
            this.Member1 = Member1;
            this.Member2 = Member2;
            this.Member8 = Member8;
        }
    }
    public struct Struct_13 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_22(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(Member0, "Member0"));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_22();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 1;
        }
        public sbyte[] Member0;
        public static Struct_13 CreateDefault()
        {
            Struct_13 ret = new Struct_13();
            ret.Member0 = new sbyte[6];
            return ret;
        }
        public Struct_13(sbyte[] Member0)
        {
            this.Member0 = Member0;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("7856fb07-7efe-4029-a4cb-4848641c40ff", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        // async
        public int s_IDBFactory_openDatabase(Struct_0 p0, int p1, char[] p2, sbyte p3, long p4, out NtApiDotNet.Ndr.Marshal.NdrEnum16 p5, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p6, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p7, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p8, out Struct_1 p9)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_0(p0);
            m.WriteInt32(p1);
            m.Write_23(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"), p1);
            m.WriteSByte(p3);
            m.WriteInt64(p4);
            _Unmarshal_Helper u = SendReceive(0, m);
            p5 = u.ReadEnum16();
            p6 = u.ReadContextHandle();
            p7 = u.ReadContextHandle();
            p8 = u.ReadContextHandle();
            p9 = u.Read_1();
            return u.ReadInt32();
        }
        // async
        public int s_IDBFactory_Handle_openDatabase_Blocked(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p1, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p2, out Struct_1 p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(1, m);
            p0 = u.ReadContextHandle();
            p1 = u.ReadContextHandle();
            p2 = u.ReadContextHandle();
            p3 = u.Read_1();
            return u.ReadInt32();
        }
        // async
        public int s_IDBFactory_deleteDatabase(Struct_0 p0, int p1, char[] p2, sbyte p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_0(p0);
            m.WriteInt32(p1);
            m.Write_23(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"), p1);
            m.WriteSByte(p3);
            _Unmarshal_Helper u = SendReceive(2, m);
            return u.ReadInt32();
        }
        // async
        public int s_IDBDatabase_createObjectStore(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, NtApiDotNet.Ndr.Marshal.NdrContextHandle p1, int p2, char[] p3, int p4, char[] p5, sbyte p6, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p7)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteContextHandle(p1);
            m.WriteInt32(p2);
            m.Write_24(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"), p2);
            m.WriteInt32(p4);
            m.WriteReferent(p5, new System.Action<char[], long>(m.Write_25), p4);
            m.WriteSByte(p6);
            _Unmarshal_Helper u = SendReceive(3, m);
            p7 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        // async
        public int s_IDBDatabase_deleteObjectStore(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, NtApiDotNet.Ndr.Marshal.NdrContextHandle p1, int p2, char[] p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteContextHandle(p1);
            m.WriteInt32(p2);
            m.Write_24(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"), p2);
            _Unmarshal_Helper u = SendReceive(4, m);
            return u.ReadInt32();
        }
        // async
        public int s_IDBDatabase_transaction(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, short p1, int p2, Struct_3[] p3, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt16(p1);
            m.WriteInt32(p2);
            m.Write_26(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p3, "p3"), p2);
            _Unmarshal_Helper u = SendReceive(5, m);
            p4 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int s_IDBDatabase_close(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(6, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int s_IDBDatabaseBlocked_close(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(7, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        // async
        public int s_IDBTransaction_openObjectStore(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, int p1, char[] p2, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt32(p1);
            m.Write_23(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"), p1);
            _Unmarshal_Helper u = SendReceive(8, m);
            p3 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int s_IDBTransaction_abortAndClose(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(9, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        // async
        public int s_IDBTransaction_commitAndClose(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, out sbyte p1, out Struct_1 p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(10, m);
            p0 = u.ReadContextHandle();
            p1 = u.ReadSByte();
            p2 = u.Read_1();
            return u.ReadInt32();
        }
        // async
        public int s_IDBObjectStore_put(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_5 p1, System.Nullable<Struct_6> p2, out Struct_6 p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_5(p1);
            m.WriteReferent(p2, new System.Action<Struct_6>(m.Write_6));
            _Unmarshal_Helper u = SendReceive(11, m);
            p3 = u.Read_6();
            return u.ReadInt32();
        }
        // async
        public int s_IDBObjectStore_add(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_5 p1, System.Nullable<Struct_6> p2, out Struct_6 p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_5(p1);
            m.WriteReferent(p2, new System.Action<Struct_6>(m.Write_6));
            _Unmarshal_Helper u = SendReceive(12, m);
            p3 = u.Read_6();
            return u.ReadInt32();
        }
        // async
        public int s_IDBObjectStore_get(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_6 p1, out Struct_8 p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_6(p1);
            _Unmarshal_Helper u = SendReceive(13, m);
            p2 = u.Read_8();
            return u.ReadInt32();
        }
        // async
        public int s_IDBObjectStore_getFromKeyRange(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_9 p1, out Struct_8 p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_9(p1);
            _Unmarshal_Helper u = SendReceive(14, m);
            p2 = u.Read_8();
            return u.ReadInt32();
        }
        // async
        public int s_IDBObjectStore_delete(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_6 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_6(p1);
            _Unmarshal_Helper u = SendReceive(15, m);
            return u.ReadInt32();
        }
        // async
        public int s_IDBObjectStore_deleteFromKeyRange(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_9 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_9(p1);
            _Unmarshal_Helper u = SendReceive(16, m);
            return u.ReadInt32();
        }
        // async
        public int s_IDBObjectStore_clear(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(17, m);
            return u.ReadInt32();
        }
        // async
        public int s_IDBObjectStore_openCursor(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, System.Nullable<Struct_9> p1, sbyte p2, short p3, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p4, out Struct_10 p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<Struct_9>(m.Write_9));
            m.WriteSByte(p2);
            m.WriteInt16(p3);
            _Unmarshal_Helper u = SendReceive(18, m);
            p4 = u.ReadContextHandle();
            p5 = u.Read_10();
            return u.ReadInt32();
        }
        // async
        public int s_IDBObjectStore_count(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, System.Nullable<Struct_9> p1, out int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<Struct_9>(m.Write_9));
            _Unmarshal_Helper u = SendReceive(19, m);
            p2 = u.ReadInt32();
            return u.ReadInt32();
        }
        // async
        public int s_IDBObjectStore_createIndex(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, int p1, char[] p2, int p3, char[] p4, sbyte p5, out long p6, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p7)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt32(p1);
            m.Write_23(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"), p1);
            m.WriteInt32(p3);
            m.WriteReferent(p4, new System.Action<char[], long>(m.Write_27), p3);
            m.WriteSByte(p5);
            _Unmarshal_Helper u = SendReceive(20, m);
            p6 = u.ReadInt64();
            p7 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        // async
        public int s_IDBObjectStore_openIndex(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(21, m);
            p2 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        // async
        public int s_IDBObjectStore_deleteIndex(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(22, m);
            return u.ReadInt32();
        }
        public int s_IDBObjectStore_close(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(23, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        // async
        public int s_IDBIndex_openCursor(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, System.Nullable<Struct_9> p1, sbyte p2, short p3, sbyte p4, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p5, out Struct_10 p6)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<Struct_9>(m.Write_9));
            m.WriteSByte(p2);
            m.WriteInt16(p3);
            m.WriteSByte(p4);
            _Unmarshal_Helper u = SendReceive(24, m);
            p5 = u.ReadContextHandle();
            p6 = u.Read_10();
            return u.ReadInt32();
        }
        // async
        public int s_IDBIndex_count(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, System.Nullable<Struct_9> p1, out int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<Struct_9>(m.Write_9));
            _Unmarshal_Helper u = SendReceive(25, m);
            p2 = u.ReadInt32();
            return u.ReadInt32();
        }
        // async
        public int s_IDBIndex_get(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_6 p1, out Struct_8 p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_6(p1);
            _Unmarshal_Helper u = SendReceive(26, m);
            p2 = u.Read_8();
            return u.ReadInt32();
        }
        // async
        public int s_IDBIndex_getFromKeyRange(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_9 p1, out Struct_8 p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_9(p1);
            _Unmarshal_Helper u = SendReceive(27, m);
            p2 = u.Read_8();
            return u.ReadInt32();
        }
        // async
        public int s_IDBIndex_getKey(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_6 p1, out Struct_6 p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_6(p1);
            _Unmarshal_Helper u = SendReceive(28, m);
            p2 = u.Read_6();
            return u.ReadInt32();
        }
        // async
        public int s_IDBIndex_getKeyFromKeyRange(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_9 p1, out Struct_6 p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_9(p1);
            _Unmarshal_Helper u = SendReceive(29, m);
            p2 = u.Read_6();
            return u.ReadInt32();
        }
        public int s_IDBIndex_close(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(30, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        // async
        public int s_IDBCursor_update(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_5 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_5(p1);
            _Unmarshal_Helper u = SendReceive(31, m);
            return u.ReadInt32();
        }
        // async
        public int s_IDBCursor_continue(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, sbyte p1, Struct_6 p2, sbyte p3, out Struct_10 p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteSByte(p1);
            m.Write_6(p2);
            m.WriteSByte(p3);
            _Unmarshal_Helper u = SendReceive(32, m);
            p4 = u.Read_10();
            return u.ReadInt32();
        }
        // async
        public int s_IDBCursor_advance(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, int p1, sbyte p2, out Struct_10 p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt32(p1);
            m.WriteSByte(p2);
            _Unmarshal_Helper u = SendReceive(33, m);
            p3 = u.Read_10();
            return u.ReadInt32();
        }
        // async
        public int s_IDBCursor_delete(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, out sbyte p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(34, m);
            p1 = u.ReadSByte();
            return u.ReadInt32();
        }
        public int s_IDBCursor_close(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(35, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int s_IDB_BrowserQuota_DeleteWebSiteDatabases(int p0, char[] p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteInt32(p0);
            m.Write_28(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"), p0);
            _Unmarshal_Helper u = SendReceive(36, m);
            return u.ReadInt32();
        }
        public int s_IDB_BrowserQuota_DeleteAllDatabases()
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(37, m);
            return u.ReadInt32();
        }
        public int s_IDB_BrowserQuota_GetSpaceConsumption(out int p0, out Struct_11[] p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(38, m);
            p0 = u.ReadInt32();
            p1 = u.ReadReferent<Struct_11[]>(new System.Func<Struct_11[]>(u.Read_29), false);
            return u.ReadInt32();
        }
        public int s_IDB_AppQuota_Uninstall(Struct_12 p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_12(p0);
            _Unmarshal_Helper u = SendReceive(39, m);
            return u.ReadInt32();
        }
    }
    #endregion
}

