//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\tellib.dll
// Interface ID: d22895ef-aff4-42c5-a5b2-b14466d34ab4
// Interface Version: 1.0



namespace rpc_d22895ef_aff4_42c5_a5b2_b14466d34ab4_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
        public void Write_1(Struct_1 p0)
        {
            WriteStruct<Struct_1>(p0);
        }
        public void Write_2(Struct_2 p0)
        {
            WriteStruct<Struct_2>(p0);
        }
        public void Write_3(Struct_3 p0)
        {
            WriteStruct<Struct_3>(p0);
        }
        public void Write_4(Struct_5 p0)
        {
            WriteStruct<Struct_5>(p0);
        }
        public void Write_5(Struct_6 p0)
        {
            WriteStruct<Struct_6>(p0);
        }
        public void Write_6(Struct_7 p0)
        {
            WriteStruct<Struct_7>(p0);
        }
        public void Write_7(Struct_8 p0)
        {
            WriteStruct<Struct_8>(p0);
        }
        public void Write_8(Struct_9 p0)
        {
            WriteStruct<Struct_9>(p0);
        }
        public void Write_9(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_10(int[] p0, long p1)
        {
            WriteConformantArray<int>(p0, p1);
        }
        public void Write_11(int[] p0, long p1)
        {
            WriteConformantArray<int>(p0, p1);
        }
        public void Write_12(int[] p0, long p1)
        {
            WriteConformantArray<int>(p0, p1);
        }
        public void Write_13(int[] p0, long p1)
        {
            WriteConformantArray<int>(p0, p1);
        }
        public void Write_14(Struct_1[] p0, long p1)
        {
            WriteConformantStructArray<Struct_1>(p0, p1);
        }
        public void Write_15(Struct_2[] p0, long p1)
        {
            WriteConformantStructArray<Struct_2>(p0, p1);
        }
        public void Write_16(Struct_3[] p0, long p1)
        {
            WriteConformantStructArray<Struct_3>(p0, p1);
        }
        public void Write_17(Struct_5[] p0, long p1)
        {
            WriteConformantStructArray<Struct_5>(p0, p1);
        }
        public void Write_18(string[] p0, long p1)
        {
            WriteConformantStringArray(p0, new System.Action<string>(this.WriteTerminatedString), p1);
        }
        public void Write_19(Struct_6[] p0, long p1)
        {
            WriteConformantStructArray<Struct_6>(p0, p1);
        }
        public void Write_20(Struct_7[] p0, long p1)
        {
            WriteConformantStructArray<Struct_7>(p0, p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
        public Struct_1 Read_1()
        {
            return ReadStruct<Struct_1>();
        }
        public Struct_2 Read_2()
        {
            return ReadStruct<Struct_2>();
        }
        public Struct_3 Read_3()
        {
            return ReadStruct<Struct_3>();
        }
        public Struct_5 Read_4()
        {
            return ReadStruct<Struct_5>();
        }
        public Struct_6 Read_5()
        {
            return ReadStruct<Struct_6>();
        }
        public Struct_7 Read_6()
        {
            return ReadStruct<Struct_7>();
        }
        public Struct_8 Read_7()
        {
            return ReadStruct<Struct_8>();
        }
        public Struct_9 Read_8()
        {
            return ReadStruct<Struct_9>();
        }
        public string[] Read_9()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public int[] Read_10()
        {
            return ReadConformantArray<int>();
        }
        public int[] Read_11()
        {
            return ReadConformantArray<int>();
        }
        public int[] Read_12()
        {
            return ReadConformantArray<int>();
        }
        public int[] Read_13()
        {
            return ReadConformantArray<int>();
        }
        public Struct_1[] Read_14()
        {
            return ReadConformantStructArray<Struct_1>();
        }
        public Struct_2[] Read_15()
        {
            return ReadConformantStructArray<Struct_2>();
        }
        public Struct_3[] Read_16()
        {
            return ReadConformantStructArray<Struct_3>();
        }
        public Struct_5[] Read_17()
        {
            return ReadConformantStructArray<Struct_5>();
        }
        public string[] Read_18()
        {
            return ReadConformantStringArray(new System.Func<string>(this.ReadConformantVaryingString));
        }
        public Struct_6[] Read_19()
        {
            return ReadConformantStructArray<Struct_6>();
        }
        public Struct_7[] Read_20()
        {
            return ReadConformantStructArray<Struct_7>();
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEmbeddedPointer<string[], long>(Member0, new System.Action<string[], long>(m.Write_9), Member8);
            m.WriteInt32(Member8);
            m.WriteEmbeddedPointer<string>(Member10, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<int[], long>(Member18, new System.Action<int[], long>(m.Write_10), Member20);
            m.WriteInt32(Member20);
            m.WriteEmbeddedPointer<int[], long>(Member28, new System.Action<int[], long>(m.Write_11), Member30);
            m.WriteInt32(Member30);
            m.WriteInt32(Member34);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEmbeddedPointer<string[]>(new System.Func<string[]>(u.Read_9), false);
            Member8 = u.ReadInt32();
            Member10 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member18 = u.ReadEmbeddedPointer<int[]>(new System.Func<int[]>(u.Read_10), false);
            Member20 = u.ReadInt32();
            Member28 = u.ReadEmbeddedPointer<int[]>(new System.Func<int[]>(u.Read_11), false);
            Member30 = u.ReadInt32();
            Member34 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string[]> Member0;
        public int Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member10;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<int[]> Member18;
        public int Member20;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<int[]> Member28;
        public int Member30;
        public int Member34;
        public static Struct_0 CreateDefault()
        {
            return new Struct_0();
        }
        public Struct_0(string[] Member0, int Member8, string Member10, int[] Member18, int Member20, int[] Member28, int Member30, int Member34)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
            this.Member28 = Member28;
            this.Member30 = Member30;
            this.Member34 = Member34;
        }
    }
    public struct Struct_1 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<string>(Member8, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member10, new System.Action<string>(m.WriteTerminatedString));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member10 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member10;
        public static Struct_1 CreateDefault()
        {
            return new Struct_1();
        }
        public Struct_1(int Member0, string Member8, string Member10)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
        }
    }
    public struct Struct_2 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEmbeddedPointer<string>(Member0, new System.Action<string>(m.WriteTerminatedString));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member0;
        public static Struct_2 CreateDefault()
        {
            return new Struct_2();
        }
        public Struct_2(string Member0)
        {
            this.Member0 = Member0;
        }
    }
    public struct Struct_3 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<string>(Member8, new System.Action<string>(m.WriteTerminatedString));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member8;
        public static Struct_3 CreateDefault()
        {
            return new Struct_3();
        }
        public Struct_3(int Member0, string Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_5 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt64(Member0);
            m.WriteInt64(Member8);
            m.WriteInt64(Member10);
            m.WriteEmbeddedPointer<string>(Member18, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member20, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member28, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<int[], long>(Member30, new System.Action<int[], long>(m.Write_12), Member38);
            m.WriteInt32(Member38);
            m.WriteEmbeddedPointer<int[], long>(Member40, new System.Action<int[], long>(m.Write_13), Member48);
            m.WriteInt32(Member48);
            m.WriteInt32(Member4C);
            m.WriteEmbeddedPointer<string>(Member50, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member58, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member60, new System.Action<string>(m.WriteTerminatedString));
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt64();
            Member8 = u.ReadInt64();
            Member10 = u.ReadInt64();
            Member18 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member20 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member28 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member30 = u.ReadEmbeddedPointer<int[]>(new System.Func<int[]>(u.Read_12), false);
            Member38 = u.ReadInt32();
            Member40 = u.ReadEmbeddedPointer<int[]>(new System.Func<int[]>(u.Read_13), false);
            Member48 = u.ReadInt32();
            Member4C = u.ReadInt32();
            Member50 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member58 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member60 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public long Member0;
        public long Member8;
        public long Member10;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member18;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member20;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member28;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<int[]> Member30;
        public int Member38;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<int[]> Member40;
        public int Member48;
        public int Member4C;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member50;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member58;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member60;
        public static Struct_5 CreateDefault()
        {
            return new Struct_5();
        }
        public Struct_5(long Member0, long Member8, long Member10, string Member18, string Member20, string Member28, int[] Member30, int Member38, int[] Member40, int Member48, int Member4C, string Member50, string Member58, string Member60)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
            this.Member28 = Member28;
            this.Member30 = Member30;
            this.Member38 = Member38;
            this.Member40 = Member40;
            this.Member48 = Member48;
            this.Member4C = Member4C;
            this.Member50 = Member50;
            this.Member58 = Member58;
            this.Member60 = Member60;
        }
    }
    public struct Struct_6 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public static Struct_6 CreateDefault()
        {
            return new Struct_6();
        }
        public Struct_6(int Member0, int Member4)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
        }
    }
    public struct Struct_7 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteEmbeddedPointer<string>(Member0, new System.Action<string>(m.WriteTerminatedString));
            m.WriteEmbeddedPointer<string>(Member8, new System.Action<string>(m.WriteTerminatedString));
            m.WriteInt32(Member10);
            m.WriteInt64(Member18);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member8 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member10 = u.ReadInt32();
            Member18 = u.ReadInt64();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member8;
        public int Member10;
        public long Member18;
        public static Struct_7 CreateDefault()
        {
            return new Struct_7();
        }
        public Struct_7(string Member0, string Member8, int Member10, long Member18)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
        }
    }
    public struct Struct_8 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt64(Member8);
            m.WriteInt64(Member10);
            m.WriteInt32(Member18);
            m.WriteFloat(Member1C);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadInt64();
            Member10 = u.ReadInt64();
            Member18 = u.ReadInt32();
            Member1C = u.ReadFloat();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public int Member0;
        public long Member8;
        public long Member10;
        public int Member18;
        public float Member1C;
        public static Struct_8 CreateDefault()
        {
            return new Struct_8();
        }
        public Struct_8(int Member0, long Member8, long Member10, int Member18, float Member1C)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member1C = Member1C;
        }
    }
    public struct Struct_9 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteInt32(Member4);
            m.WriteInt32(Member8);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member4 = u.ReadInt32();
            Member8 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public int Member4;
        public int Member8;
        public static Struct_9 CreateDefault()
        {
            return new Struct_9();
        }
        public Struct_9(int Member0, int Member4, int Member8)
        {
            this.Member0 = Member0;
            this.Member4 = Member4;
            this.Member8 = Member8;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("d22895ef-aff4-42c5-a5b2-b14466d34ab4", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public int UtcEventTranscriptApi_GetDiagnosticDataAccessAllowed(out NtApiDotNet.Ndr.Marshal.NdrEnum16 p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            _Unmarshal_Helper u = SendReceive(0, m);
            p0 = u.ReadEnum16();
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_CreateDiagnosticDataQueryApiSession(NtApiDotNet.Ndr.Marshal.NdrEnum16 p0, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteEnum16(p0);
            _Unmarshal_Helper u = SendReceive(1, m);
            p1 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_CloseDiagnosticDataQueryApiSession(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(2, m);
            p0 = u.ReadContextHandle();
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_FetchTranscriptStats(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_0 p1, out int p2, out long p3, out long p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_0(p1);
            _Unmarshal_Helper u = SendReceive(3, m);
            p2 = u.ReadInt32();
            p3 = u.ReadInt64();
            p4 = u.ReadInt64();
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_FetchTranscriptRecordPayload(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, long p1, out string p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt64(p1);
            _Unmarshal_Helper u = SendReceive(4, m);
            p2 = u.ReadReferent<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_FetchKnownTags(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string p1, out Struct_1[] p2, out int p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            _Unmarshal_Helper u = SendReceive(5, m);
            p2 = u.ReadReferent<Struct_1[]>(new System.Func<Struct_1[]>(u.Read_14), false);
            p3 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_FetchKnownProducers(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, out Struct_2[] p1, out int p2)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(6, m);
            p1 = u.ReadReferent<Struct_2[]>(new System.Func<Struct_2[]>(u.Read_15), false);
            p2 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_FetchKnownProducerCategories(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string p1, out Struct_3[] p2, out int p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p1, "p1"));
            _Unmarshal_Helper u = SendReceive(7, m);
            p2 = u.ReadReferent<Struct_3[]>(new System.Func<Struct_3[]>(u.Read_16), false);
            p3 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_IsSampledIn(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, System.Guid p1, System.Nullable<System.Guid> p2, string p3, System.Nullable<int> p4, string p5, System.Nullable<int> p6, System.Nullable<long> p7, out int p8)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteGuid(p1);
            m.WriteReferent(p2, new System.Action<System.Guid>(m.WriteGuid));
            m.WriteReferent(p3, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p4, new System.Action<int>(m.WriteInt32));
            m.WriteReferent(p5, new System.Action<string>(m.WriteTerminatedString));
            m.WriteReferent(p6, new System.Action<int>(m.WriteInt32));
            m.WriteReferent(p7, new System.Action<long>(m.WriteInt64));
            _Unmarshal_Helper u = SendReceive(8, m);
            p8 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_FetchTranscriptRecordsPage(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_0 p1, int p2, int p3, long p4, out Struct_5[] p5, out int p6)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_0(p1);
            m.WriteInt32(p2);
            m.WriteInt32(p3);
            m.WriteInt64(p4);
            _Unmarshal_Helper u = SendReceive(9, m);
            p5 = u.ReadReferent<Struct_5[]>(new System.Func<Struct_5[]>(u.Read_17), false);
            p6 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_CancelFetchOperations(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(10, m);
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_FetchEventPerCategoryDistribution(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string[] p1, int p2, out Struct_6[] p3, out int p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<string[], long>(m.Write_18), p2);
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(11, m);
            p3 = u.ReadReferent<Struct_6[]>(new System.Func<Struct_6[]>(u.Read_19), false);
            p4 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_FetchEventPerBinaryDistribution(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string[] p1, int p2, int p3, out Struct_7[] p4, out int p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<string[], long>(m.Write_18), p2);
            m.WriteInt32(p2);
            m.WriteInt32(p3);
            _Unmarshal_Helper u = SendReceive(12, m);
            p4 = u.ReadReferent<Struct_7[]>(new System.Func<Struct_7[]>(u.Read_20), false);
            p5 = u.ReadInt32();
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_FetchDiagnosticsStats(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, string[] p1, int p2, out Struct_8 p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteReferent(p1, new System.Action<string[], long>(m.Write_18), p2);
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(13, m);
            p3 = u.Read_7();
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_SetTranscriptConfiguration(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, Struct_9 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.Write_8(p1);
            _Unmarshal_Helper u = SendReceive(14, m);
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_GetTranscriptConfiguration(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, out Struct_9 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(15, m);
            p1 = u.Read_8();
            return u.ReadInt32();
        }
        public int UtcEventTranscriptApi_GetDiagnosticSessionAccessLevel(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, out NtApiDotNet.Ndr.Marshal.NdrEnum16 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(16, m);
            p1 = u.ReadEnum16();
            return u.ReadInt32();
        }
    }
    #endregion
}

