//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\seclogon.dll
// Interface ID: 12b81e99-f207-4a4c-85d3-77b42f76fd14
// Interface Version: 1.0



namespace rpc_12b81e99_f207_4a4c_85d3_77b42f76fd14_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(Struct_0 p0)
        {
            WriteStruct<Struct_0>(p0);
        }
        public void Write_1(Struct_1 p0)
        {
            WriteStruct<Struct_1>(p0);
        }
        public void Write_2(Struct_2 p0)
        {
            WriteStruct<Struct_2>(p0);
        }
        public void Write_3(Struct_3 p0)
        {
            WriteStruct<Struct_3>(p0);
        }
        public void Write_4(Struct_4 p0)
        {
            WriteStruct<Struct_4>(p0);
        }
        public void Write_5(char[] p0, long p1, long p2)
        {
            WriteConformantVaryingArray<char>(p0, p1, p2);
        }
        public void Write_6(string p0, long p1)
        {
            WriteConformantVaryingString(p0, p1);
        }
        public void Write_7(string p0, long p1)
        {
            WriteConformantVaryingString(p0, p1);
        }
        public void Write_8(string p0, long p1)
        {
            WriteConformantVaryingString(p0, p1);
        }
        public void Write_9(byte[] p0, long p1)
        {
            WriteConformantArray<byte>(p0, p1);
        }
        public void Write_10(sbyte[] p0, long p1)
        {
            WriteConformantArray<sbyte>(p0, p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public Struct_0 Read_0()
        {
            return ReadStruct<Struct_0>();
        }
        public Struct_1 Read_1()
        {
            return ReadStruct<Struct_1>();
        }
        public Struct_2 Read_2()
        {
            return ReadStruct<Struct_2>();
        }
        public Struct_3 Read_3()
        {
            return ReadStruct<Struct_3>();
        }
        public Struct_4 Read_4()
        {
            return ReadStruct<Struct_4>();
        }
        public char[] Read_5()
        {
            return ReadConformantVaryingArray<char>();
        }
        public byte[] Read_6()
        {
            return ReadConformantArray<byte>();
        }
        public sbyte[] Read_7()
        {
            return ReadConformantArray<sbyte>();
        }
    }
    #endregion
    #region Complex Types
    public struct Struct_0 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.Write_1(Member0);
            m.Write_1(Member10);
            m.Write_1(Member20);
            m.Write_1(Member30);
            m.Write_1(Member40);
            m.Write_1(Member50);
            m.Write_2(Member60);
            m.Write_3(MemberC8);
            m.WriteInt32(MemberD8);
            m.WriteInt32(MemberDC);
            m.WriteInt32(MemberE0);
            m.WriteInt32(MemberE4);
            m.WriteInt32(MemberE8);
            m.WriteInt32(MemberEC);
            m.WriteInt64(MemberF0);
            m.WriteInt64(MemberF8);
            m.WriteInt64(Member100);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.Read_1();
            Member10 = u.Read_1();
            Member20 = u.Read_1();
            Member30 = u.Read_1();
            Member40 = u.Read_1();
            Member50 = u.Read_1();
            Member60 = u.Read_2();
            MemberC8 = u.Read_3();
            MemberD8 = u.ReadInt32();
            MemberDC = u.ReadInt32();
            MemberE0 = u.ReadInt32();
            MemberE4 = u.ReadInt32();
            MemberE8 = u.ReadInt32();
            MemberEC = u.ReadInt32();
            MemberF0 = u.ReadInt64();
            MemberF8 = u.ReadInt64();
            Member100 = u.ReadInt64();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public Struct_1 Member0;
        public Struct_1 Member10;
        public Struct_1 Member20;
        public Struct_1 Member30;
        public Struct_1 Member40;
        public Struct_1 Member50;
        public Struct_2 Member60;
        public Struct_3 MemberC8;
        public int MemberD8;
        public int MemberDC;
        public int MemberE0;
        public int MemberE4;
        public int MemberE8;
        public int MemberEC;
        public long MemberF0;
        public long MemberF8;
        public long Member100;
        public static Struct_0 CreateDefault()
        {
            return new Struct_0();
        }
        public Struct_0(
                    Struct_1 Member0, 
                    Struct_1 Member10, 
                    Struct_1 Member20, 
                    Struct_1 Member30, 
                    Struct_1 Member40, 
                    Struct_1 Member50, 
                    Struct_2 Member60, 
                    Struct_3 MemberC8, 
                    int MemberD8, 
                    int MemberDC, 
                    int MemberE0, 
                    int MemberE4, 
                    int MemberE8, 
                    int MemberEC, 
                    long MemberF0, 
                    long MemberF8, 
                    long Member100)
        {
            this.Member0 = Member0;
            this.Member10 = Member10;
            this.Member20 = Member20;
            this.Member30 = Member30;
            this.Member40 = Member40;
            this.Member50 = Member50;
            this.Member60 = Member60;
            this.MemberC8 = MemberC8;
            this.MemberD8 = MemberD8;
            this.MemberDC = MemberDC;
            this.MemberE0 = MemberE0;
            this.MemberE4 = MemberE4;
            this.MemberE8 = MemberE8;
            this.MemberEC = MemberEC;
            this.MemberF0 = MemberF0;
            this.MemberF8 = MemberF8;
            this.Member100 = Member100;
        }
    }
    public struct Struct_1 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt16(Member0);
            m.WriteInt16(Member2);
            m.WriteEmbeddedPointer<char[], long, long>(Member8, new System.Action<char[], long, long>(m.Write_5), Member2, Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt16();
            Member2 = u.ReadInt16();
            Member8 = u.ReadEmbeddedPointer<char[]>(new System.Func<char[]>(u.Read_5), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public short Member0;
        public short Member2;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<char[]> Member8;
        public static Struct_1 CreateDefault()
        {
            return new Struct_1();
        }
        public Struct_1(short Member0, short Member2, char[] Member8)
        {
            this.Member0 = Member0;
            this.Member2 = Member2;
            this.Member8 = Member8;
        }
    }
    public struct Struct_2 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<string, long>(Member8, new System.Action<string, long>(m.Write_6), 1025);
            m.WriteEmbeddedPointer<string, long>(Member10, new System.Action<string, long>(m.Write_7), 1025);
            m.WriteEmbeddedPointer<string, long>(Member18, new System.Action<string, long>(m.Write_8), 1025);
            m.WriteInt32(Member20);
            m.WriteInt32(Member24);
            m.WriteInt32(Member28);
            m.WriteInt32(Member2C);
            m.WriteInt32(Member30);
            m.WriteInt32(Member34);
            m.WriteInt32(Member38);
            m.WriteInt32(Member3C);
            m.WriteInt16(Member40);
            m.WriteInt16(Member42);
            m.WriteEmbeddedPointer<byte[], long>(Member48, new System.Action<byte[], long>(m.Write_9), Member42);
            m.WriteInt64(Member50);
            m.WriteInt64(Member58);
            m.WriteInt64(Member60);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member10 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member18 = u.ReadEmbeddedPointer<string>(new System.Func<string>(u.ReadConformantVaryingString), false);
            Member20 = u.ReadInt32();
            Member24 = u.ReadInt32();
            Member28 = u.ReadInt32();
            Member2C = u.ReadInt32();
            Member30 = u.ReadInt32();
            Member34 = u.ReadInt32();
            Member38 = u.ReadInt32();
            Member3C = u.ReadInt32();
            Member40 = u.ReadInt16();
            Member42 = u.ReadInt16();
            Member48 = u.ReadEmbeddedPointer<byte[]>(new System.Func<byte[]>(u.Read_6), false);
            Member50 = u.ReadInt64();
            Member58 = u.ReadInt64();
            Member60 = u.ReadInt64();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member8;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member10;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<string> Member18;
        public int Member20;
        public int Member24;
        public int Member28;
        public int Member2C;
        public int Member30;
        public int Member34;
        public int Member38;
        public int Member3C;
        public short Member40;
        public short Member42;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<byte[]> Member48;
        public long Member50;
        public long Member58;
        public long Member60;
        public static Struct_2 CreateDefault()
        {
            return new Struct_2();
        }
        public Struct_2(
                    int Member0, 
                    string Member8, 
                    string Member10, 
                    string Member18, 
                    int Member20, 
                    int Member24, 
                    int Member28, 
                    int Member2C, 
                    int Member30, 
                    int Member34, 
                    int Member38, 
                    int Member3C, 
                    short Member40, 
                    short Member42, 
                    byte[] Member48, 
                    long Member50, 
                    long Member58, 
                    long Member60)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member18 = Member18;
            this.Member20 = Member20;
            this.Member24 = Member24;
            this.Member28 = Member28;
            this.Member2C = Member2C;
            this.Member30 = Member30;
            this.Member34 = Member34;
            this.Member38 = Member38;
            this.Member3C = Member3C;
            this.Member40 = Member40;
            this.Member42 = Member42;
            this.Member48 = Member48;
            this.Member50 = Member50;
            this.Member58 = Member58;
            this.Member60 = Member60;
        }
    }
    public struct Struct_3 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt32(Member0);
            m.WriteEmbeddedPointer<sbyte[], long>(Member8, new System.Action<sbyte[], long>(m.Write_10), Member0);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt32();
            Member8 = u.ReadEmbeddedPointer<sbyte[]>(new System.Func<sbyte[]>(u.Read_7), false);
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 4;
        }
        public int Member0;
        public NtApiDotNet.Ndr.Marshal.NdrEmbeddedPointer<sbyte[]> Member8;
        public static Struct_3 CreateDefault()
        {
            return new Struct_3();
        }
        public Struct_3(int Member0, sbyte[] Member8)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
        }
    }
    public struct Struct_4 : NtApiDotNet.Ndr.Marshal.INdrStructure
    {
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Marshal(NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer m)
        {
            Marshal(((_Marshal_Helper)(m)));
        }
        private void Marshal(_Marshal_Helper m)
        {
            m.WriteInt64(Member0);
            m.WriteInt64(Member8);
            m.WriteInt32(Member10);
            m.WriteInt32(Member14);
            m.WriteInt32(Member18);
        }
        void NtApiDotNet.Ndr.Marshal.INdrStructure.Unmarshal(NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer u)
        {
            Unmarshal(((_Unmarshal_Helper)(u)));
        }
        private void Unmarshal(_Unmarshal_Helper u)
        {
            Member0 = u.ReadInt64();
            Member8 = u.ReadInt64();
            Member10 = u.ReadInt32();
            Member14 = u.ReadInt32();
            Member18 = u.ReadInt32();
        }
        int NtApiDotNet.Ndr.Marshal.INdrStructure.GetAlignment()
        {
            return 8;
        }
        public long Member0;
        public long Member8;
        public int Member10;
        public int Member14;
        public int Member18;
        public static Struct_4 CreateDefault()
        {
            return new Struct_4();
        }
        public Struct_4(long Member0, long Member8, int Member10, int Member14, int Member18)
        {
            this.Member0 = Member0;
            this.Member8 = Member8;
            this.Member10 = Member10;
            this.Member14 = Member14;
            this.Member18 = Member18;
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("12b81e99-f207-4a4c-85d3-77b42f76fd14", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public void SeclCreateProcessWithLogonW(Struct_0 p0, out Struct_4 p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.Write_0(p0);
            _Unmarshal_Helper u = SendReceive(0, m);
            p1 = u.Read_4();
        }
    }
    #endregion
}

