//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Source Executable: c:\windows\system32\regsvc.dll
// Interface ID: da5a86c5-12c2-4943-ab30-7f74a813d853
// Interface Version: 1.0



namespace rpc_da5a86c5_12c2_4943_ab30_7f74a813d853_1_0
{
    
    #region Marshal Helpers
    internal class _Marshal_Helper : NtApiDotNet.Ndr.Marshal.NdrMarshalBuffer
    {
        public void Write_0(System.Guid[] p0, long p1, long p2)
        {
            WriteConformantVaryingArrayCallback<System.Guid>(p0, new System.Action<System.Guid>(this.WriteGuid), p1, p2);
        }
        public void Write_1(sbyte[] p0, long p1, long p2)
        {
            WriteConformantVaryingArray<sbyte>(p0, p1, p2);
        }
        public void Write_2(sbyte[] p0, long p1, long p2)
        {
            WriteConformantVaryingArray<sbyte>(p0, p1, p2);
        }
        public void Write_3(sbyte[] p0, long p1, long p2)
        {
            WriteConformantVaryingArray<sbyte>(p0, p1, p2);
        }
        public void Write_4(sbyte[] p0, long p1)
        {
            WriteConformantArray<sbyte>(p0, p1);
        }
    }
    internal class _Unmarshal_Helper : NtApiDotNet.Ndr.Marshal.NdrUnmarshalBuffer
    {
        public _Unmarshal_Helper(NtApiDotNet.Win32.Rpc.RpcClientResponse r) : 
                base(r.NdrBuffer, r.Handles, r.DataRepresentation)
        {
        }
        public _Unmarshal_Helper(byte[] ba) : 
                base(ba)
        {
        }
        public System.Guid[] Read_0()
        {
            return ReadConformantVaryingArrayCallback<System.Guid>(new System.Func<System.Guid>(this.ReadGuid));
        }
        public sbyte[] Read_1()
        {
            return ReadConformantVaryingArray<sbyte>();
        }
        public sbyte[] Read_2()
        {
            return ReadConformantVaryingArray<sbyte>();
        }
        public sbyte[] Read_3()
        {
            return ReadConformantVaryingArray<sbyte>();
        }
        public sbyte[] Read_4()
        {
            return ReadConformantArray<sbyte>();
        }
    }
    #endregion
    #region Client Implementation
    public sealed class Client : NtApiDotNet.Win32.Rpc.RpcClientBase
    {
        public Client() : 
                base("da5a86c5-12c2-4943-ab30-7f74a813d853", 1, 0)
        {
        }
        private _Unmarshal_Helper SendReceive(int p, _Marshal_Helper m)
        {
            return new _Unmarshal_Helper(SendReceive(p, m.DataRepresentation, m.ToArray(), m.Handles));
        }
        public uint PerflibV2EnumerateCounterSet(string p0, int p1, out int p2, out int p3, out System.Guid[] p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(0, m);
            p2 = u.ReadInt32();
            p3 = u.ReadInt32();
            p4 = u.Read_0();
            return u.ReadUInt32();
        }
        public uint PerflibV2QueryCounterSetRegistrationInfo(string p0, System.Guid p1, int p2, int p3, int p4, out int p5, out int p6, out sbyte[] p7)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteGuid(p1);
            m.WriteInt32(p2);
            m.WriteInt32(p3);
            m.WriteInt32(p4);
            _Unmarshal_Helper u = SendReceive(1, m);
            p5 = u.ReadInt32();
            p6 = u.ReadInt32();
            p7 = u.Read_1();
            return u.ReadUInt32();
        }
        public uint PerflibV2EnumerateCounterSetInstances(string p0, System.Guid p1, int p2, out int p3, out int p4, out sbyte[] p5)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            m.WriteGuid(p1);
            m.WriteInt32(p2);
            _Unmarshal_Helper u = SendReceive(2, m);
            p3 = u.ReadInt32();
            p4 = u.ReadInt32();
            p5 = u.Read_2();
            return u.ReadUInt32();
        }
        public uint PerflibV2OpenQueryHandle(string p0, out NtApiDotNet.Ndr.Marshal.NdrContextHandle p1)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteTerminatedString(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p0, "p0"));
            _Unmarshal_Helper u = SendReceive(3, m);
            p1 = u.ReadContextHandle();
            return u.ReadUInt32();
        }
        public uint PerflibV2CloseQueryHandle(ref NtApiDotNet.Ndr.Marshal.NdrContextHandle p0)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            _Unmarshal_Helper u = SendReceive(4, m);
            p0 = u.ReadContextHandle();
            return u.ReadUInt32();
        }
        public uint PerflibV2QueryCounterInfo(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, int p1, out int p2, out int p3, out sbyte[] p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(5, m);
            p2 = u.ReadInt32();
            p3 = u.ReadInt32();
            p4 = u.Read_3();
            return u.ReadUInt32();
        }
        public uint PerflibV2QueryCounterData(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, int p1, out int p2, out int p3, out sbyte[] p4)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt32(p1);
            _Unmarshal_Helper u = SendReceive(6, m);
            p2 = u.ReadInt32();
            p3 = u.ReadInt32();
            p4 = u.Read_3();
            return u.ReadUInt32();
        }
        public uint PerflibV2ValidateCounters(NtApiDotNet.Ndr.Marshal.NdrContextHandle p0, int p1, ref sbyte[] p2, int p3)
        {
            _Marshal_Helper m = new _Marshal_Helper();
            m.WriteContextHandle(p0);
            m.WriteInt32(p1);
            m.Write_4(NtApiDotNet.Win32.Rpc.RpcUtils.CheckNull(p2, "p2"), p1);
            m.WriteInt32(p3);
            _Unmarshal_Helper u = SendReceive(7, m);
            p2 = u.Read_4();
            return u.ReadUInt32();
        }
    }
    #endregion
}

